# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `snaky_hash` gem.
# Please instead update this file by running `bin/tapioca gem snaky_hash`.

# This is the namespace for this gem
module SnakyHash; end

class SnakyHash::Snake < ::Module
  # @return [Snake] a new instance of Snake
  def initialize(key_type: T.unsafe(nil)); end

  def included(base); end
end

module SnakyHash::Snake::SnakyModulizer
  class << self
    def to_mod(key_type); end
  end
end

class SnakyHash::StringKeyed < ::Hashie::Mash; end
class SnakyHash::SymbolKeyed < ::Hashie::Mash; end

module SnakyHash::Version
  extend ::VersionGem::Basic
  extend ::VersionGem::Api
end

SnakyHash::Version::VERSION = T.let(T.unsafe(nil), String)
