// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_confirmations.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const createEmailConfirmation = `-- name: CreateEmailConfirmation :one
INSERT INTO email_confirmations (
    email,
    event,
    code,
    started_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, event, code, started_at, succeeded_at, created_at, updated_at
`

type CreateEmailConfirmationParams struct {
	Email     string    `json:"email"`
	Event     int32     `json:"event"`
	Code      string    `json:"code"`
	StartedAt time.Time `json:"started_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// 新しいメール確認情報を作成する
func (q *Queries) CreateEmailConfirmation(ctx context.Context, arg CreateEmailConfirmationParams) (EmailConfirmation, error) {
	row := q.db.QueryRowContext(ctx, createEmailConfirmation,
		arg.Email,
		arg.Event,
		arg.Code,
		arg.StartedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmailConfirmation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Event,
		&i.Code,
		&i.StartedAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveEmailConfirmationByEmailAndEvent = `-- name: GetActiveEmailConfirmationByEmailAndEvent :one
SELECT id, email, event, code, started_at, succeeded_at, created_at, updated_at FROM email_confirmations
WHERE email = $1
  AND event = $2
  AND succeeded_at IS NULL
  AND started_at > NOW() - INTERVAL '15 minutes'
ORDER BY started_at DESC
LIMIT 1
`

type GetActiveEmailConfirmationByEmailAndEventParams struct {
	Email string `json:"email"`
	Event int32  `json:"event"`
}

// メールアドレスとイベント種別で有効なメール確認情報を取得する
// 有効条件: succeeded_at IS NULL（未確認）かつ started_at が15分以内
func (q *Queries) GetActiveEmailConfirmationByEmailAndEvent(ctx context.Context, arg GetActiveEmailConfirmationByEmailAndEventParams) (EmailConfirmation, error) {
	row := q.db.QueryRowContext(ctx, getActiveEmailConfirmationByEmailAndEvent, arg.Email, arg.Event)
	var i EmailConfirmation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Event,
		&i.Code,
		&i.StartedAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailConfirmationByID = `-- name: GetEmailConfirmationByID :one
SELECT id, email, event, code, started_at, succeeded_at, created_at, updated_at FROM email_confirmations WHERE id = $1
`

// IDでメール確認情報を取得する
func (q *Queries) GetEmailConfirmationByID(ctx context.Context, id string) (EmailConfirmation, error) {
	row := q.db.QueryRowContext(ctx, getEmailConfirmationByID, id)
	var i EmailConfirmation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Event,
		&i.Code,
		&i.StartedAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmailConfirmationSucceededAt = `-- name: UpdateEmailConfirmationSucceededAt :exec
UPDATE email_confirmations
SET succeeded_at = $2, updated_at = $3
WHERE id = $1
`

type UpdateEmailConfirmationSucceededAtParams struct {
	ID          string       `json:"id"`
	SucceededAt sql.NullTime `json:"succeeded_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

// メール確認を完了状態に更新する
func (q *Queries) UpdateEmailConfirmationSucceededAt(ctx context.Context, arg UpdateEmailConfirmationSucceededAtParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailConfirmationSucceededAt, arg.ID, arg.SucceededAt, arg.UpdatedAt)
	return err
}
