// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_grants.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createOAuthGrant = `-- name: CreateOAuthGrant :one
INSERT INTO oauth_grants (
    oauth_application_id,
    space_id,
    space_member_id,
    scopes,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4::text[],
    $5,
    $5
) RETURNING id, oauth_application_id, space_id, space_member_id, scopes, revoked_at, created_at, updated_at
`

type CreateOAuthGrantParams struct {
	OauthApplicationID string    `json:"oauth_application_id"`
	SpaceID            string    `json:"space_id"`
	SpaceMemberID      string    `json:"space_member_id"`
	Scopes             []string  `json:"scopes"`
	Now                time.Time `json:"now"`
}

// OAuthアプリの許可を作成する
func (q *Queries) CreateOAuthGrant(ctx context.Context, arg CreateOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRowContext(ctx, createOAuthGrant,
		arg.OauthApplicationID,
		arg.SpaceID,
		arg.SpaceMemberID,
		pq.Array(arg.Scopes),
		arg.Now,
	)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.OauthApplicationID,
		&i.SpaceID,
		&i.SpaceMemberID,
		pq.Array(&i.Scopes),
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOAuthGrantByID = `-- name: FindOAuthGrantByID :one
SELECT id, oauth_application_id, space_id, space_member_id, scopes, revoked_at, created_at, updated_at FROM oauth_grants
WHERE id = $1
  AND space_id = $2
`

type FindOAuthGrantByIDParams struct {
	ID      string `json:"id"`
	SpaceID string `json:"space_id"`
}

// IDでOAuthアプリの許可を取得する
func (q *Queries) FindOAuthGrantByID(ctx context.Context, arg FindOAuthGrantByIDParams) (OauthGrant, error) {
	row := q.db.QueryRowContext(ctx, findOAuthGrantByID, arg.ID, arg.SpaceID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.OauthApplicationID,
		&i.SpaceID,
		&i.SpaceMemberID,
		pq.Array(&i.Scopes),
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUnrevokedOAuthGrantByApplicationAndSpaceMember = `-- name: FindUnrevokedOAuthGrantByApplicationAndSpaceMember :one
SELECT id, oauth_application_id, space_id, space_member_id, scopes, revoked_at, created_at, updated_at FROM oauth_grants
WHERE oauth_application_id = $1
  AND space_id = $2
  AND space_member_id = $3
  AND revoked_at IS NULL
`

type FindUnrevokedOAuthGrantByApplicationAndSpaceMemberParams struct {
	OauthApplicationID string `json:"oauth_application_id"`
	SpaceID            string `json:"space_id"`
	SpaceMemberID      string `json:"space_member_id"`
}

// スペースメンバーがOAuthアプリに与えている、失効していない許可を取得する
func (q *Queries) FindUnrevokedOAuthGrantByApplicationAndSpaceMember(ctx context.Context, arg FindUnrevokedOAuthGrantByApplicationAndSpaceMemberParams) (OauthGrant, error) {
	row := q.db.QueryRowContext(ctx, findUnrevokedOAuthGrantByApplicationAndSpaceMember, arg.OauthApplicationID, arg.SpaceID, arg.SpaceMemberID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.OauthApplicationID,
		&i.SpaceID,
		&i.SpaceMemberID,
		pq.Array(&i.Scopes),
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnrevokedOAuthGrantsBySpaceMember = `-- name: ListUnrevokedOAuthGrantsBySpaceMember :many
SELECT id, oauth_application_id, space_id, space_member_id, scopes, revoked_at, created_at, updated_at FROM oauth_grants
WHERE space_id = $1
  AND space_member_id = $2
  AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListUnrevokedOAuthGrantsBySpaceMemberParams struct {
	SpaceID       string `json:"space_id"`
	SpaceMemberID string `json:"space_member_id"`
}

// スペースメンバーが与えている失効していない許可を、新しい順に取得する。削除したアプリの
// 許可は削除のときに失効しているため、ここには出ない
func (q *Queries) ListUnrevokedOAuthGrantsBySpaceMember(ctx context.Context, arg ListUnrevokedOAuthGrantsBySpaceMemberParams) ([]OauthGrant, error) {
	rows, err := q.db.QueryContext(ctx, listUnrevokedOAuthGrantsBySpaceMember, arg.SpaceID, arg.SpaceMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthGrant{}
	for rows.Next() {
		var i OauthGrant
		if err := rows.Scan(
			&i.ID,
			&i.OauthApplicationID,
			&i.SpaceID,
			&i.SpaceMemberID,
			pq.Array(&i.Scopes),
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :one
WITH revoked_grant AS (
    UPDATE oauth_grants
    SET revoked_at = $1::timestamptz, updated_at = $1
    WHERE oauth_grants.id = $2
      AND oauth_grants.space_id = $3
      AND oauth_grants.space_member_id = $4
      AND oauth_grants.revoked_at IS NULL
    RETURNING oauth_grants.id, oauth_grants.oauth_application_id, oauth_grants.space_id, oauth_grants.space_member_id, oauth_grants.scopes, oauth_grants.revoked_at, oauth_grants.created_at, oauth_grants.updated_at
),
revoked_access_tokens AS (
    UPDATE oauth_access_tokens
    SET revoked_at = $1::timestamptz, updated_at = $1
    WHERE oauth_access_tokens.oauth_grant_id IN (SELECT revoked_grant.id FROM revoked_grant)
      AND oauth_access_tokens.space_id = $3
      AND oauth_access_tokens.revoked_at IS NULL
),
revoked_refresh_tokens AS (
    UPDATE oauth_refresh_tokens
    SET revoked_at = $1::timestamptz, updated_at = $1
    WHERE oauth_refresh_tokens.oauth_grant_id IN (SELECT revoked_grant.id FROM revoked_grant)
      AND oauth_refresh_tokens.space_id = $3
      AND oauth_refresh_tokens.revoked_at IS NULL
)
SELECT id, oauth_application_id, space_id, space_member_id, scopes, revoked_at, created_at, updated_at FROM revoked_grant
`

type RevokeOAuthGrantParams struct {
	Now           time.Time `json:"now"`
	ID            string    `json:"id"`
	SpaceID       string    `json:"space_id"`
	SpaceMemberID string    `json:"space_member_id"`
}

type RevokeOAuthGrantRow struct {
	ID                 string       `json:"id"`
	OauthApplicationID string       `json:"oauth_application_id"`
	SpaceID            string       `json:"space_id"`
	SpaceMemberID      string       `json:"space_member_id"`
	Scopes             []string     `json:"scopes"`
	RevokedAt          sql.NullTime `json:"revoked_at"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
}

// スペースメンバー自身のOAuthアプリの許可と、許可に属するアクセストークン・リフレッシュトークンを
// すべて失効する。1文で行うため、許可だけが失効してトークンが使える状態は途中にも残らない。
// 対象が無いか既に失効している場合は何も変えずに行を返さない
func (q *Queries) RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (RevokeOAuthGrantRow, error) {
	row := q.db.QueryRowContext(ctx, revokeOAuthGrant,
		arg.Now,
		arg.ID,
		arg.SpaceID,
		arg.SpaceMemberID,
	)
	var i RevokeOAuthGrantRow
	err := row.Scan(
		&i.ID,
		&i.OauthApplicationID,
		&i.SpaceID,
		&i.SpaceMemberID,
		pq.Array(&i.Scopes),
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
