// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_editors.sql

package query

import (
	"context"
	"time"
)

const createPageEditor = `-- name: CreatePageEditor :one
INSERT INTO page_editors (space_id, page_id, space_member_id, last_page_modified_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, page_id, space_member_id, last_page_modified_at, created_at, updated_at
`

type CreatePageEditorParams struct {
	SpaceID            string    `json:"space_id"`
	PageID             string    `json:"page_id"`
	SpaceMemberID      string    `json:"space_member_id"`
	LastPageModifiedAt time.Time `json:"last_page_modified_at"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

// ページ編集者を作成する
func (q *Queries) CreatePageEditor(ctx context.Context, arg CreatePageEditorParams) (PageEditor, error) {
	row := q.db.QueryRowContext(ctx, createPageEditor,
		arg.SpaceID,
		arg.PageID,
		arg.SpaceMemberID,
		arg.LastPageModifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PageEditor
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.PageID,
		&i.SpaceMemberID,
		&i.LastPageModifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPageEditorByPageAndSpaceMember = `-- name: FindPageEditorByPageAndSpaceMember :one
SELECT id, space_id, page_id, space_member_id, last_page_modified_at, created_at, updated_at FROM page_editors WHERE page_id = $1 AND space_member_id = $2
`

type FindPageEditorByPageAndSpaceMemberParams struct {
	PageID        string `json:"page_id"`
	SpaceMemberID string `json:"space_member_id"`
}

// ページIDとスペースメンバーIDでページ編集者を取得する
func (q *Queries) FindPageEditorByPageAndSpaceMember(ctx context.Context, arg FindPageEditorByPageAndSpaceMemberParams) (PageEditor, error) {
	row := q.db.QueryRowContext(ctx, findPageEditorByPageAndSpaceMember, arg.PageID, arg.SpaceMemberID)
	var i PageEditor
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.PageID,
		&i.SpaceMemberID,
		&i.LastPageModifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePageEditorLastPageModifiedAt = `-- name: UpdatePageEditorLastPageModifiedAt :one
UPDATE page_editors
SET last_page_modified_at = $2, updated_at = $3
WHERE id = $1 AND space_id = $4
RETURNING id, space_id, page_id, space_member_id, last_page_modified_at, created_at, updated_at
`

type UpdatePageEditorLastPageModifiedAtParams struct {
	ID                 string    `json:"id"`
	LastPageModifiedAt time.Time `json:"last_page_modified_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	SpaceID            string    `json:"space_id"`
}

// ページ編集者のlast_page_modified_atを更新する
func (q *Queries) UpdatePageEditorLastPageModifiedAt(ctx context.Context, arg UpdatePageEditorLastPageModifiedAtParams) (PageEditor, error) {
	row := q.db.QueryRowContext(ctx, updatePageEditorLastPageModifiedAt,
		arg.ID,
		arg.LastPageModifiedAt,
		arg.UpdatedAt,
		arg.SpaceID,
	)
	var i PageEditor
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.PageID,
		&i.SpaceMemberID,
		&i.LastPageModifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
