// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package query

import (
	"context"
)

const getSpaceByIdentifier = `-- name: GetSpaceByIdentifier :one
SELECT id, identifier, name, plan, joined_at, discarded_at, created_at, updated_at FROM spaces WHERE identifier = $1 AND discarded_at IS NULL
`

// 識別子でスペースを取得する（削除されていないスペースのみ）
func (q *Queries) GetSpaceByIdentifier(ctx context.Context, identifier string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByIdentifier, identifier)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Name,
		&i.Plan,
		&i.JoinedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSpacesByUser = `-- name: ListActiveSpacesByUser :many
SELECT s.id, s.identifier, s.name, s.plan, s.joined_at, s.discarded_at, s.created_at, s.updated_at FROM spaces s
INNER JOIN space_members sm ON sm.space_id = s.id
WHERE sm.user_id = $1
  AND sm.active = TRUE
  AND s.discarded_at IS NULL
ORDER BY sm.joined_at DESC
`

// ユーザーが参加中（active）かつ削除されていないスペースの一覧を取得する
// Rails 版 current_user.active_space_records 相当
// 並び順はユーザーがスペースに参加した日の降順（最近参加したスペースが上）
func (q *Queries) ListActiveSpacesByUser(ctx context.Context, userID string) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSpacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Name,
			&i.Plan,
			&i.JoinedAt,
			&i.DiscardedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
