// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestion_page_revisions.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const createSuggestionPageRevision = `-- name: CreateSuggestionPageRevision :one
INSERT INTO suggestion_page_revisions (space_id, suggestion_page_id, editor_space_member_id, title, body, body_html, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, space_id, suggestion_page_id, editor_space_member_id, title, body, body_html, created_at, updated_at
`

type CreateSuggestionPageRevisionParams struct {
	SpaceID             string         `json:"space_id"`
	SuggestionPageID    string         `json:"suggestion_page_id"`
	EditorSpaceMemberID string         `json:"editor_space_member_id"`
	Title               sql.NullString `json:"title"`
	Body                string         `json:"body"`
	BodyHtml            string         `json:"body_html"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

// 編集提案ページリビジョンを作成する
func (q *Queries) CreateSuggestionPageRevision(ctx context.Context, arg CreateSuggestionPageRevisionParams) (SuggestionPageRevision, error) {
	row := q.db.QueryRowContext(ctx, createSuggestionPageRevision,
		arg.SpaceID,
		arg.SuggestionPageID,
		arg.EditorSpaceMemberID,
		arg.Title,
		arg.Body,
		arg.BodyHtml,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SuggestionPageRevision
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.SuggestionPageID,
		&i.EditorSpaceMemberID,
		&i.Title,
		&i.Body,
		&i.BodyHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSuggestionPageRevisionsBySuggestionPageID = `-- name: DeleteSuggestionPageRevisionsBySuggestionPageID :exec
DELETE FROM suggestion_page_revisions WHERE suggestion_page_id = $1 AND space_id = $2
`

type DeleteSuggestionPageRevisionsBySuggestionPageIDParams struct {
	SuggestionPageID string `json:"suggestion_page_id"`
	SpaceID          string `json:"space_id"`
}

// 編集提案ページIDでリビジョンを一括削除する（スペースIDでスコープ）
func (q *Queries) DeleteSuggestionPageRevisionsBySuggestionPageID(ctx context.Context, arg DeleteSuggestionPageRevisionsBySuggestionPageIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteSuggestionPageRevisionsBySuggestionPageID, arg.SuggestionPageID, arg.SpaceID)
	return err
}

const findLatestSuggestionPageRevision = `-- name: FindLatestSuggestionPageRevision :one
SELECT id, space_id, suggestion_page_id, editor_space_member_id, title, body, body_html, created_at, updated_at FROM suggestion_page_revisions
WHERE suggestion_page_id = $1 AND space_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type FindLatestSuggestionPageRevisionParams struct {
	SuggestionPageID string `json:"suggestion_page_id"`
	SpaceID          string `json:"space_id"`
}

// 編集提案ページの最新リビジョンを取得する（スペースIDでスコープ）
func (q *Queries) FindLatestSuggestionPageRevision(ctx context.Context, arg FindLatestSuggestionPageRevisionParams) (SuggestionPageRevision, error) {
	row := q.db.QueryRowContext(ctx, findLatestSuggestionPageRevision, arg.SuggestionPageID, arg.SpaceID)
	var i SuggestionPageRevision
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.SuggestionPageID,
		&i.EditorSpaceMemberID,
		&i.Title,
		&i.Body,
		&i.BodyHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuggestionPageRevisionsBySuggestionPageID = `-- name: ListSuggestionPageRevisionsBySuggestionPageID :many
SELECT id, space_id, suggestion_page_id, editor_space_member_id, title, body, body_html, created_at, updated_at FROM suggestion_page_revisions
WHERE suggestion_page_id = $1 AND space_id = $2
ORDER BY created_at ASC
`

type ListSuggestionPageRevisionsBySuggestionPageIDParams struct {
	SuggestionPageID string `json:"suggestion_page_id"`
	SpaceID          string `json:"space_id"`
}

// 編集提案ページIDでリビジョン一覧を取得する（作成日時の昇順）
func (q *Queries) ListSuggestionPageRevisionsBySuggestionPageID(ctx context.Context, arg ListSuggestionPageRevisionsBySuggestionPageIDParams) ([]SuggestionPageRevision, error) {
	rows, err := q.db.QueryContext(ctx, listSuggestionPageRevisionsBySuggestionPageID, arg.SuggestionPageID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuggestionPageRevision{}
	for rows.Next() {
		var i SuggestionPageRevision
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.SuggestionPageID,
			&i.EditorSpaceMemberID,
			&i.Title,
			&i.Body,
			&i.BodyHtml,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
