// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_passwords.sql

package query

import (
	"context"
)

const getUserPasswordByUserID = `-- name: GetUserPasswordByUserID :one
SELECT id, user_id, password_digest, created_at, updated_at FROM user_passwords WHERE user_id = $1
`

// ユーザーIDでパスワード情報を取得する
func (q *Queries) GetUserPasswordByUserID(ctx context.Context, userID string) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByUserID, userID)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
