// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_passwords.sql

package query

import (
	"context"
	"time"
)

const createUserPassword = `-- name: CreateUserPassword :one
INSERT INTO user_passwords (
    user_id,
    password_digest,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, password_digest, created_at, updated_at
`

type CreateUserPasswordParams struct {
	UserID         string    `json:"user_id"`
	PasswordDigest string    `json:"password_digest"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// 新しいユーザーパスワードを作成する
func (q *Queries) CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, createUserPassword,
		arg.UserID,
		arg.PasswordDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordByUserID = `-- name: GetUserPasswordByUserID :one
SELECT id, user_id, password_digest, created_at, updated_at FROM user_passwords WHERE user_id = $1
`

// ユーザーIDでパスワード情報を取得する
func (q *Queries) GetUserPasswordByUserID(ctx context.Context, userID string) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByUserID, userID)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
