services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - postgresql
    environment:
      BINDING: 0.0.0.0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - app_gems_data:/usr/local/bundle

  postgresql:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  app_gems_data:
  postgresql_data:
