services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - postgresql
      - chrome
    environment:
      BINDING: 0.0.0.0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - app_gems_data:/usr/local/bundle

  postgresql:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - postgresql17_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  chrome:
    image: selenium/standalone-chromium:136.0.7103.113

volumes:
  app_gems_data:
  postgresql17_data:
