version: '3.7'

services:
  postgresql:
    image: postgres:14.2
    ports:
      - 45432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgresql_data:
