version: "3.7"

services:
  webpack:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    command: /bin/ash -c 'yarn webpack:start'
    volumes:
      - .:/nonoto
      - node_modules_vol:/nonoto/node_modules
    ports:
      - 8080:8080
  postgresql:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ../_postgresql/nonoto/data:/var/lib/postgresql/data

volumes:
  # Exclude the bundle/node_modules directory
  # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
  node_modules_vol:
