version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.local
    env_file:
      - ./api/.env.development
      - ./api/.env.development.local
    command: /bin/ash -c 'rm -rf tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    depends_on:
      - postgresql
    ports:
      - 4000:3000
    tty: true
    volumes:
      - ./api:/app
      - nonoto_gems_vol:/usr/local/bundle

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile.local
    env_file:
      - ./web/.env.development
      - ./web/.env.development.local
    command: /bin/ash -c 'npm run dev'
    volumes:
      - ./web:/app
      - nonoto_node_modules_vol:/app/node_modules
    ports:
      - 4001:3000
    tty: true

  postgresql:
    image: postgres:12.3-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../_postgresql/nonoto/data:/var/lib/postgresql/data

volumes:
  nonoto_gems_vol:
  nonoto_node_modules_vol:
