version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.local
    env_file:
      - ./backend/.env.development
      - ./backend/.env.development.local
    command: /bin/ash -c 'rm -rf tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    depends_on:
      - postgresql
    ports:
      - 3001:3000
    tty: true
    volumes:
      - ./backend:/app
      - gems_vol:/usr/local/bundle

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./app/frontend/Dockerfile
  #   command: /bin/ash -c 'yarn webpack:start'
  #   volumes:
  #     - .:/nonoto
  #     - node_modules_vol:/nonoto/node_modules
  #   ports:
  #     - 8080:8080

  postgresql:
    image: postgres:12.3-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../_postgresql/nonoto/data:/var/lib/postgresql/data

volumes:
  gems_vol:
  node_modules_vol:
