version: '3.7'

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: /bin/ash -c 'rm -rf tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0'
    depends_on:
      - postgresql
      - webpack
    env_file:
      - .env.development
      - .env.development.local
    environment:
      LANG: C.UTF-8
    ports:
      - 3000:3000
    stdin_open: true # for Pry
    tty: true # for Pry
    volumes:
      - .:/workspace
      - gems_vol:/usr/local/bundle
      - node_modules_vol:/workspace/node_modules
  webpack:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile.local
    command: /bin/ash -c 'npm run webpack:start'
    volumes:
      - .:/workspace
      - node_modules_vol:/workspace/node_modules
    ports:
      - 8080:8080
  postgresql:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.0.5-alpine
    ports:
      - 6379:6379
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

volumes:
  # Exclude the gems/node_modules directory
  # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
  gems_vol:
  node_modules_vol:
