services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - postgresql
      - minio
    environment:
      BINDING: 0.0.0.0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - app_gems_data:/usr/local/bundle

  postgresql:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - postgresql17_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin
      MINIO_DOMAIN: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    volumes:
      - minio_data:/data
    networks:
      default:
        aliases:
          - wikino-user-contents.minio

volumes:
  app_gems_data:
  postgresql17_data:
  minio_data:
