FROM ruby:2.7.2-buster

LABEL maintainer="https://www.kiraka.net" \
  description="A place for writing notes."

RUN apt update && \
  apt install -y \
  git \
  postgresql \
  imagemagick

ENV RAILS_ENV=development

# Set to run `ls` in Pry
# https://github.com/pry/pry/issues/1494#issuecomment-162336567
ENV PAGER=busybox\ less

WORKDIR /workspace/

COPY Gemfile* ./
RUN gem install bundler && \
  bundle install -j$(getconf _NPROCESSORS_ONLN)

EXPOSE 3000
