services:
  postgresql:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - postgresql17_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  chrome:
    image: selenium/standalone-chromium:136.0.7103.113

volumes:
  postgresql17_data:
