# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EmailForm::Edit`.
# Please instead update this file by running `bin/tapioca dsl EmailForm::Edit`.


class EmailForm::Edit
  sig { returns(T.nilable(::String)) }
  def new_email; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def new_email=(value); end
end
