# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Emails::EditForm`.
# Please instead update this file by running `bin/tapioca dsl Emails::EditForm`.


class Emails::EditForm
  sig { returns(T.nilable(::String)) }
  def new_email; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def new_email=(value); end
end
