# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SpaceDestroyConfirmationForm`.
# Please instead update this file by running `bin/tapioca dsl SpaceDestroyConfirmationForm`.


class SpaceDestroyConfirmationForm
  sig { returns(T.nilable(::String)) }
  def space_name; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def space_name=(value); end
end
