# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TopicDestroyConfirmationForm`.
# Please instead update this file by running `bin/tapioca dsl TopicDestroyConfirmationForm`.


class TopicDestroyConfirmationForm
  sig { returns(T.nilable(::String)) }
  def topic_name; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def topic_name=(value); end
end
