# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Attachments::CreationForm`.
# Please instead update this file by running `bin/tapioca dsl Attachments::CreationForm`.


class Attachments::CreationForm
  sig { returns(T.nilable(::String)) }
  def blob_signed_id; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def blob_signed_id=(value); end
end
