default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

  queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_QUEUE_URL") %>
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

production:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

  queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_QUEUE_URL") %>
    migrations_paths: db/queue_migrate
