test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

cloudflare_r2:
  service: S3
  endpoint: <%= ENV["WIKINO_ACTIVE_STORAGE_ENDPOINT"] %>
  access_key_id: <%= ENV["WIKINO_ACTIVE_STORAGE_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["WIKINO_ACTIVE_STORAGE_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["WIKINO_ACTIVE_STORAGE_BUCKET"] %>
  region: <%= ENV["WIKINO_ACTIVE_STORAGE_REGION"] %>
  # https://github.com/rails/rails/issues/54374
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
