shared:
  email_domain: <%= ENV["WIKINO_EMAIL_DOMAIN"] %>
  host: <%= ENV["WIKINO_HOST"] %>
  reserved_atnames:
    - admin
    - administrator
    - administrators
    - admins
    - atname
    - example
    - me
    - self
  reserved_space_identifiers:
    - about
    - api
    - app
    - web
    - www
