# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserSessionForm::TwoFactorVerification`.
# Please instead update this file by running `bin/tapioca dsl UserSessionForm::TwoFactorVerification`.


class UserSessionForm::TwoFactorVerification
  sig { returns(T.nilable(::String)) }
  def code; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def code=(value); end
end
