// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TopicVisibility.
const (
	Private TopicVisibility = "private"
	Public  TopicVisibility = "public"
)

// Valid indicates whether the value is a known member of the TopicVisibility enum.
func (e TopicVisibility) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// NewPage 作成するページです。
type NewPage struct {
	// Body ページの本文 (Markdown) です。空文字列にもできます。
	Body PageBodyInput `json:"body"`

	// Title ページのタイトルです。トピック内で重複できません。
	// `/`・`\`・`:`・制御文字は使えず、先頭と末尾にスペースを置けません。
	Title PageTitleInput `json:"title"`

	// TopicNumber ページを作成するトピックの番号です。
	TopicNumber int32 `json:"topic_number"`
}

// NextCursor 次のページを取得するカーソルです。`cursor` パラメーターに渡します。続きが無い場合は `null` です。
type NextCursor = string

// Page ページです。
type Page struct {
	// Body ページの本文 (Markdown) です。
	Body string `json:"body"`

	// Id ページのIDです。
	Id openapi_types.UUID `json:"id"`

	// ModifiedAt ページの内容を最後に更新した日時です (RFC 3339のUTC。例: `2026-09-01T12:34:56.123456Z`)。
	// 秒未満はマイクロ秒まで含み、末尾の0は省きます。`modified_since` にそのまま渡せます。
	ModifiedAt time.Time `json:"modified_at"`

	// Number スペース内のページの番号です。パスの `page_number` に使います。
	Number int32 `json:"number"`

	// Title ページのタイトルです。タイトルの無いページでは `null` です。
	Title *string `json:"title"`

	// TopicNumber ページが属するトピックの番号です。
	TopicNumber int32 `json:"topic_number"`
}

// PageBodyInput ページの本文 (Markdown) です。空文字列にもできます。
type PageBodyInput = string

// PageList ページの一覧の1ページです。
type PageList struct {
	// Items このページのページです。
	Items []Page `json:"items"`

	// NextCursor 次のページを取得するカーソルです。`cursor` パラメーターに渡します。続きが無い場合は `null` です。
	NextCursor *NextCursor `json:"next_cursor"`
}

// PagePatch ページの更新内容です (JSON Merge Patch)。含めた項目だけを更新します。
// どの項目も `null` にはできません。定義していない項目を含めると422を返します。
type PagePatch struct {
	// Body ページの本文 (Markdown) です。空文字列にもできます。
	Body *PageBodyInput `json:"body,omitempty"`

	// Title ページのタイトルです。トピック内で重複できません。
	// `/`・`\`・`:`・制御文字は使えず、先頭と末尾にスペースを置けません。
	Title *PageTitleInput `json:"title,omitempty"`
}

// PageTitleInput ページのタイトルです。トピック内で重複できません。
// `/`・`\`・`:`・制御文字は使えず、先頭と末尾にスペースを置けません。
type PageTitleInput = string

// ProblemDetails RFC 9457のProblem Detailsです。
type ProblemDetails struct {
	// Detail この発生に固有の説明です。
	Detail *string `json:"detail"`

	// Errors フィールド単位の問題です。`type` が `validation-failed` の問題にだけ含みます。
	Errors *[]ProblemDetailsError `json:"errors,omitempty"`

	// Status HTTPステータスコードです。
	Status int `json:"status"`

	// Title 問題の種類の短い説明です。
	Title string `json:"title"`

	// Type 問題の種類を表すURIです。種類ごとに変わらない値で、プログラムでの判別に使えます。
	// ステータスコード以上の情報を持たない問題では `about:blank` です。
	Type string `json:"type"`
}

// ProblemDetailsError リクエストの検証で見つかった1つの問題です。
type ProblemDetailsError struct {
	// Detail 問題の説明です。
	Detail string `json:"detail"`

	// Parameter 問題のあったパラメーター (パス・クエリ・ヘッダー) の名前です。パラメーター以外の問題では `null` です。
	Parameter *string `json:"parameter"`

	// Pointer リクエスト本文の問題の箇所を指すJSON Pointer (URIフラグメント形式。例 `#/title`) です。本文以外の問題では `null` です。
	Pointer *string `json:"pointer"`
}

// Space スペースです。
type Space struct {
	// Id スペースのIDです。
	Id openapi_types.UUID `json:"id"`

	// Identifier スペースの識別子です。パスの `space_identifier` に使います。
	Identifier string `json:"identifier"`

	// Name スペースの名前です。
	Name string `json:"name"`
}

// SpaceMember スペースのメンバーです。
type SpaceMember struct {
	// Atname アットネーム (`@` の後に続く名前) です。
	Atname string `json:"atname"`

	// Id メンバーのIDです。同じ人でもスペースごとに異なります。
	Id openapi_types.UUID `json:"id"`

	// Name 表示名です。設定していない場合は空文字列です。
	Name string `json:"name"`
}

// Topic トピックです。
type Topic struct {
	// Description トピックの説明です。設定していない場合は空文字列です。
	Description string `json:"description"`

	// Id トピックのIDです。
	Id openapi_types.UUID `json:"id"`

	// Name トピックの名前です。
	Name string `json:"name"`

	// Number スペース内のトピックの番号です。パスの `topic_number` に使います。
	Number int32 `json:"number"`

	// Visibility トピックの公開範囲です。`public` は誰でも見られる公開トピック、`private` はトピックに参加しているメンバーなどだけが見られる非公開トピックです。
	Visibility TopicVisibility `json:"visibility"`
}

// TopicVisibility トピックの公開範囲です。`public` は誰でも見られる公開トピック、`private` はトピックに参加しているメンバーなどだけが見られる非公開トピックです。
type TopicVisibility string

// TopicList トピックの一覧の1ページです。
type TopicList struct {
	// Items このページのトピックです。
	Items []Topic `json:"items"`

	// NextCursor 次のページを取得するカーソルです。`cursor` パラメーターに渡します。続きが無い場合は `null` です。
	NextCursor *NextCursor `json:"next_cursor"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// PageNumber defines model for PageNumber.
type PageNumber = int32

// SpaceIdentifier defines model for SpaceIdentifier.
type SpaceIdentifier = string

// TopicNumber defines model for TopicNumber.
type TopicNumber = int32

// BadRequest RFC 9457のProblem Detailsです。
type BadRequest = ProblemDetails

// Forbidden RFC 9457のProblem Detailsです。
type Forbidden = ProblemDetails

// NotFound RFC 9457のProblem Detailsです。
type NotFound = ProblemDetails

// PreconditionFailed RFC 9457のProblem Detailsです。
type PreconditionFailed = ProblemDetails

// PreconditionRequired RFC 9457のProblem Detailsです。
type PreconditionRequired = ProblemDetails

// TooManyRequests RFC 9457のProblem Detailsです。
type TooManyRequests = ProblemDetails

// Unauthorized RFC 9457のProblem Detailsです。
type Unauthorized = ProblemDetails

// UnexpectedError RFC 9457のProblem Detailsです。
type UnexpectedError = ProblemDetails

// UnsupportedMediaType RFC 9457のProblem Detailsです。
type UnsupportedMediaType = ProblemDetails

// UnsupportedPatchMediaType RFC 9457のProblem Detailsです。
type UnsupportedPatchMediaType = ProblemDetails

// ValidationFailed RFC 9457のProblem Detailsです。
type ValidationFailed = ProblemDetails

// ListPagesParams defines parameters for ListPages.
type ListPagesParams struct {
	// TopicNumber このトピック番号のトピックのページだけを返します。
	// 存在しないトピックや見られないトピックを指定すると、空の一覧を返します。
	TopicNumber *int32 `form:"topic_number,omitempty" json:"topic_number,omitempty"`

	// ModifiedSince この日時 (RFC 3339) 以降に更新されたページだけを返します。指定した日時ちょうどに更新されたページも含みます。
	ModifiedSince *time.Time `form:"modified_since,omitempty" json:"modified_since,omitempty"`

	// Cursor 続きのページを取得するためのカーソルです。前のページの応答の `next_cursor` をそのまま渡します。
	// 中身の形式は公開しておらず、予告なく変わることがあります。省略すると最初のページを返します。
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit 1ページの件数です。100を超える値は100として扱います。
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPageParams defines parameters for GetPage.
type GetPageParams struct {
	// IfNoneMatch 前回の応答の `ETag` です。ページの応答が変わっていなければ304を返します。
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// UpdatePageParams defines parameters for UpdatePage.
type UpdatePageParams struct {
	// IfMatch 更新の前提にするページの `ETag` です。ページの今の `ETag` と一致する場合だけ更新します。
	// 省略すると428を返します。
	IfMatch *string `json:"If-Match,omitempty"`
}

// ListTopicsParams defines parameters for ListTopics.
type ListTopicsParams struct {
	// Cursor 続きのページを取得するためのカーソルです。前のページの応答の `next_cursor` をそのまま渡します。
	// 中身の形式は公開しておらず、予告なく変わることがあります。省略すると最初のページを返します。
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit 1ページの件数です。100を超える値は100として扱います。
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = NewPage

// UpdatePageApplicationMergePatchPlusJSONRequestBody defines body for UpdatePage for application/merge-patch+json ContentType.
type UpdatePageApplicationMergePatchPlusJSONRequestBody = PagePatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetOpenAPIDescription OpenAPI記述を取得する
	// (GET /openapi.yaml)
	GetOpenAPIDescription(w http.ResponseWriter, r *http.Request)
	// GetSpace トークンを束縛したスペースを取得する
	// (GET /spaces/{space_identifier})
	GetSpace(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier)
	// GetCurrentSpaceMember トークンの持ち主のメンバーを取得する
	// (GET /spaces/{space_identifier}/members/me)
	GetCurrentSpaceMember(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier)
	// ListPages ページの一覧を取得する
	// (GET /spaces/{space_identifier}/pages)
	ListPages(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, params ListPagesParams)
	// CreatePage ページを作成する
	// (POST /spaces/{space_identifier}/pages)
	CreatePage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier)
	// GetPage ページを取得する
	// (GET /spaces/{space_identifier}/pages/{page_number})
	GetPage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, pageNumber PageNumber, params GetPageParams)
	// UpdatePage ページを更新する
	// (PATCH /spaces/{space_identifier}/pages/{page_number})
	UpdatePage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, pageNumber PageNumber, params UpdatePageParams)
	// ListTopics トピックの一覧を取得する
	// (GET /spaces/{space_identifier}/topics)
	ListTopics(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, params ListTopicsParams)
	// GetTopic トピックを取得する
	// (GET /spaces/{space_identifier}/topics/{topic_number})
	GetTopic(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, topicNumber TopicNumber)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetOpenAPIDescription OpenAPI記述を取得する
// (GET /openapi.yaml)
func (_ Unimplemented) GetOpenAPIDescription(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSpace トークンを束縛したスペースを取得する
// (GET /spaces/{space_identifier})
func (_ Unimplemented) GetSpace(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrentSpaceMember トークンの持ち主のメンバーを取得する
// (GET /spaces/{space_identifier}/members/me)
func (_ Unimplemented) GetCurrentSpaceMember(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListPages ページの一覧を取得する
// (GET /spaces/{space_identifier}/pages)
func (_ Unimplemented) ListPages(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, params ListPagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreatePage ページを作成する
// (POST /spaces/{space_identifier}/pages)
func (_ Unimplemented) CreatePage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPage ページを取得する
// (GET /spaces/{space_identifier}/pages/{page_number})
func (_ Unimplemented) GetPage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, pageNumber PageNumber, params GetPageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdatePage ページを更新する
// (PATCH /spaces/{space_identifier}/pages/{page_number})
func (_ Unimplemented) UpdatePage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, pageNumber PageNumber, params UpdatePageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTopics トピックの一覧を取得する
// (GET /spaces/{space_identifier}/topics)
func (_ Unimplemented) ListTopics(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, params ListTopicsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTopic トピックを取得する
// (GET /spaces/{space_identifier}/topics/{topic_number})
func (_ Unimplemented) GetTopic(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, topicNumber TopicNumber) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetOpenAPIDescription operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPIDescription(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPIDescription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpace operation middleware
func (siw *ServerInterfaceWrapper) GetSpace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpace(w, r, spaceIdentifier)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSpaceMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSpaceMember(w, r, spaceIdentifier)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPages operation middleware
func (siw *ServerInterfaceWrapper) ListPages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPagesParams

	// ------------- Optional query parameter "topic_number" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "topic_number", r.URL.Query(), &params.TopicNumber, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "topic_number"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topic_number", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "modified_since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "modified_since", r.URL.Query(), &params.ModifiedSince, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "modified_since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modified_since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPages(w, r, spaceIdentifier, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePage operation middleware
func (siw *ServerInterfaceWrapper) CreatePage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePage(w, r, spaceIdentifier)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPage operation middleware
func (siw *ServerInterfaceWrapper) GetPage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	// ------------- Path parameter "page_number" -------------
	var pageNumber PageNumber

	err = runtime.BindStyledParameterWithOptions("simple", "page_number", chi.URLParam(r, "page_number"), &pageNumber, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_number", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPageParams

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPage(w, r, spaceIdentifier, pageNumber, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePage operation middleware
func (siw *ServerInterfaceWrapper) UpdatePage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	// ------------- Path parameter "page_number" -------------
	var pageNumber PageNumber

	err = runtime.BindStyledParameterWithOptions("simple", "page_number", chi.URLParam(r, "page_number"), &pageNumber, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_number", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdatePageParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePage(w, r, spaceIdentifier, pageNumber, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopics operation middleware
func (siw *ServerInterfaceWrapper) ListTopics(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTopicsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopics(w, r, spaceIdentifier, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopic operation middleware
func (siw *ServerInterfaceWrapper) GetTopic(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "space_identifier" -------------
	var spaceIdentifier SpaceIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "space_identifier", chi.URLParam(r, "space_identifier"), &spaceIdentifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "space_identifier", Err: err})
		return
	}

	// ------------- Path parameter "topic_number" -------------
	var topicNumber TopicNumber

	err = runtime.BindStyledParameterWithOptions("simple", "topic_number", chi.URLParam(r, "topic_number"), &topicNumber, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topic_number", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopic(w, r, spaceIdentifier, topicNumber)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{space_identifier}", wrapper.GetSpace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{space_identifier}/members/me", wrapper.GetCurrentSpaceMember)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{space_identifier}/topics", wrapper.ListTopics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{space_identifier}/topics/{topic_number}", wrapper.GetTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{space_identifier}/pages", wrapper.ListPages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/spaces/{space_identifier}/pages", wrapper.CreatePage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{space_identifier}/pages/{page_number}", wrapper.GetPage)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/spaces/{space_identifier}/pages/{page_number}", wrapper.UpdatePage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/openapi.yaml", wrapper.GetOpenAPIDescription)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse ProblemDetails

type ForbiddenResponseHeaders struct {
	WWWAuthenticate string
}
type ForbiddenApplicationProblemPlusJSONResponse struct {
	Body ProblemDetails

	Headers ForbiddenResponseHeaders
}

type NotFoundApplicationProblemPlusJSONResponse ProblemDetails

type PreconditionFailedApplicationProblemPlusJSONResponse ProblemDetails

type PreconditionRequiredApplicationProblemPlusJSONResponse ProblemDetails

type TooManyRequestsResponseHeaders struct {
	RateLimit       *string
	RateLimitPolicy *string
	RetryAfter      int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body ProblemDetails

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedApplicationProblemPlusJSONResponse struct {
	Body ProblemDetails

	Headers UnauthorizedResponseHeaders
}

type UnexpectedErrorApplicationProblemPlusJSONResponse ProblemDetails

type UnsupportedMediaTypeResponseHeaders struct {
	AcceptPost string
}
type UnsupportedMediaTypeApplicationProblemPlusJSONResponse struct {
	Body ProblemDetails

	Headers UnsupportedMediaTypeResponseHeaders
}

type UnsupportedPatchMediaTypeResponseHeaders struct {
	AcceptPatch string
}
type UnsupportedPatchMediaTypeApplicationProblemPlusJSONResponse struct {
	Body ProblemDetails

	Headers UnsupportedPatchMediaTypeResponseHeaders
}

type ValidationFailedApplicationProblemPlusJSONResponse ProblemDetails

type GetOpenAPIDescriptionRequestObject struct {
}

type GetOpenAPIDescriptionResponseObject interface {
	VisitGetOpenAPIDescriptionResponse(w http.ResponseWriter) error
}

type GetOpenAPIDescription200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOpenAPIDescription200ApplicationyamlResponse) VisitGetOpenAPIDescriptionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetOpenAPIDescriptiondefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response GetOpenAPIDescriptiondefaultApplicationProblemPlusJSONResponse) VisitGetOpenAPIDescriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpaceRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
}

type GetSpaceResponseObject interface {
	VisitGetSpaceResponse(w http.ResponseWriter) error
}

type GetSpace200ResponseHeaders struct {
	RateLimit       *string
	RateLimitPolicy *string
}

type GetSpace200JSONResponse struct {
	Body    Space
	Headers GetSpace200ResponseHeaders
}

func (response GetSpace200JSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpace401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetSpace401ApplicationProblemPlusJSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpace404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetSpace404ApplicationProblemPlusJSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpace429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetSpace429ApplicationProblemPlusJSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpacedefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response GetSpacedefaultApplicationProblemPlusJSONResponse) VisitGetSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSpaceMemberRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
}

type GetCurrentSpaceMemberResponseObject interface {
	VisitGetCurrentSpaceMemberResponse(w http.ResponseWriter) error
}

type GetCurrentSpaceMember200ResponseHeaders struct {
	RateLimit       *string
	RateLimitPolicy *string
}

type GetCurrentSpaceMember200JSONResponse struct {
	Body    SpaceMember
	Headers GetCurrentSpaceMember200ResponseHeaders
}

func (response GetCurrentSpaceMember200JSONResponse) VisitGetCurrentSpaceMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSpaceMember401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetCurrentSpaceMember401ApplicationProblemPlusJSONResponse) VisitGetCurrentSpaceMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSpaceMember404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetCurrentSpaceMember404ApplicationProblemPlusJSONResponse) VisitGetCurrentSpaceMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSpaceMember429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetCurrentSpaceMember429ApplicationProblemPlusJSONResponse) VisitGetCurrentSpaceMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSpaceMemberdefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response GetCurrentSpaceMemberdefaultApplicationProblemPlusJSONResponse) VisitGetCurrentSpaceMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListPagesRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
	Params          ListPagesParams
}

type ListPagesResponseObject interface {
	VisitListPagesResponse(w http.ResponseWriter) error
}

type ListPages200ResponseHeaders struct {
	Link            *string
	RateLimit       *string
	RateLimitPolicy *string
}

type ListPages200JSONResponse struct {
	Body    PageList
	Headers ListPages200ResponseHeaders
}

func (response ListPages200JSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Link != nil {
		w.Header().Set("Link", fmt.Sprint(*response.Headers.Link))
	}
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPages401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListPages401ApplicationProblemPlusJSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPages403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListPages403ApplicationProblemPlusJSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListPages404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListPages404ApplicationProblemPlusJSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListPages422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response ListPages422ApplicationProblemPlusJSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListPages429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListPages429ApplicationProblemPlusJSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListPagesdefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response ListPagesdefaultApplicationProblemPlusJSONResponse) VisitListPagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePageRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
	Body            *CreatePageJSONRequestBody
}

type CreatePageResponseObject interface {
	VisitCreatePageResponse(w http.ResponseWriter) error
}

type CreatePage201ResponseHeaders struct {
	ETag            string
	Location        string
	RateLimit       *string
	RateLimitPolicy *string
}

type CreatePage201JSONResponse struct {
	Body    Page
	Headers CreatePage201ResponseHeaders
}

func (response CreatePage201JSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreatePage400ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreatePage401ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreatePage403ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreatePage404ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage415ApplicationProblemPlusJSONResponse struct {
	UnsupportedMediaTypeApplicationProblemPlusJSONResponse
}

func (response CreatePage415ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Accept-Post", fmt.Sprint(response.Headers.AcceptPost))
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response CreatePage422ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePage429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response CreatePage429ApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePagedefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response CreatePagedefaultApplicationProblemPlusJSONResponse) VisitCreatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPageRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
	PageNumber      PageNumber      `json:"page_number"`
	Params          GetPageParams
}

type GetPageResponseObject interface {
	VisitGetPageResponse(w http.ResponseWriter) error
}

type GetPage200ResponseHeaders struct {
	ETag            string
	RateLimit       *string
	RateLimitPolicy *string
}

type GetPage200JSONResponse struct {
	Body    Page
	Headers GetPage200ResponseHeaders
}

func (response GetPage200JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPage304ResponseHeaders struct {
	ETag            string
	RateLimit       *string
	RateLimitPolicy *string
}

type GetPage304Response struct {
	Headers GetPage304ResponseHeaders
}

func (response GetPage304Response) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(304)
	return nil
}

type GetPage401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetPage401ApplicationProblemPlusJSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPage403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetPage403ApplicationProblemPlusJSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetPage404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetPage404ApplicationProblemPlusJSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPage422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response GetPage422ApplicationProblemPlusJSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetPage429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetPage429ApplicationProblemPlusJSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetPagedefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response GetPagedefaultApplicationProblemPlusJSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePageRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
	PageNumber      PageNumber      `json:"page_number"`
	Params          UpdatePageParams
	Body            *UpdatePageApplicationMergePatchPlusJSONRequestBody
}

type UpdatePageResponseObject interface {
	VisitUpdatePageResponse(w http.ResponseWriter) error
}

type UpdatePage200ResponseHeaders struct {
	ETag            string
	RateLimit       *string
	RateLimitPolicy *string
}

type UpdatePage200JSONResponse struct {
	Body    Page
	Headers UpdatePage200ResponseHeaders
}

func (response UpdatePage200JSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UpdatePage400ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdatePage401ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdatePage403ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdatePage404ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response UpdatePage412ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage415ApplicationProblemPlusJSONResponse struct {
	UnsupportedPatchMediaTypeApplicationProblemPlusJSONResponse
}

func (response UpdatePage415ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Accept-Patch", fmt.Sprint(response.Headers.AcceptPatch))
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response UpdatePage422ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage428ApplicationProblemPlusJSONResponse struct {
	PreconditionRequiredApplicationProblemPlusJSONResponse
}

func (response UpdatePage428ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePage429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response UpdatePage429ApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePagedefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response UpdatePagedefaultApplicationProblemPlusJSONResponse) VisitUpdatePageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopicsRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
	Params          ListTopicsParams
}

type ListTopicsResponseObject interface {
	VisitListTopicsResponse(w http.ResponseWriter) error
}

type ListTopics200ResponseHeaders struct {
	Link            *string
	RateLimit       *string
	RateLimitPolicy *string
}

type ListTopics200JSONResponse struct {
	Body    TopicList
	Headers ListTopics200ResponseHeaders
}

func (response ListTopics200JSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Link != nil {
		w.Header().Set("Link", fmt.Sprint(*response.Headers.Link))
	}
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopics401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListTopics401ApplicationProblemPlusJSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopics403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListTopics403ApplicationProblemPlusJSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopics404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListTopics404ApplicationProblemPlusJSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopics422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response ListTopics422ApplicationProblemPlusJSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopics429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListTopics429ApplicationProblemPlusJSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListTopicsdefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response ListTopicsdefaultApplicationProblemPlusJSONResponse) VisitListTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopicRequestObject struct {
	SpaceIdentifier SpaceIdentifier `json:"space_identifier"`
	TopicNumber     TopicNumber     `json:"topic_number"`
}

type GetTopicResponseObject interface {
	VisitGetTopicResponse(w http.ResponseWriter) error
}

type GetTopic200ResponseHeaders struct {
	RateLimit       *string
	RateLimitPolicy *string
}

type GetTopic200JSONResponse struct {
	Body    Topic
	Headers GetTopic200ResponseHeaders
}

func (response GetTopic200JSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopic401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetTopic401ApplicationProblemPlusJSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopic403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetTopic403ApplicationProblemPlusJSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopic404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetTopic404ApplicationProblemPlusJSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopic422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response GetTopic422ApplicationProblemPlusJSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopic429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetTopic429ApplicationProblemPlusJSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimit != nil {
		w.Header().Set("RateLimit", fmt.Sprint(*response.Headers.RateLimit))
	}
	if response.Headers.RateLimitPolicy != nil {
		w.Header().Set("RateLimit-Policy", fmt.Sprint(*response.Headers.RateLimitPolicy))
	}
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopicdefaultApplicationProblemPlusJSONResponse struct {
	Body       ProblemDetails
	StatusCode int
}

func (response GetTopicdefaultApplicationProblemPlusJSONResponse) VisitGetTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetOpenAPIDescription OpenAPI記述を取得する
	// (GET /openapi.yaml)
	GetOpenAPIDescription(ctx context.Context, request GetOpenAPIDescriptionRequestObject) (GetOpenAPIDescriptionResponseObject, error)
	// GetSpace トークンを束縛したスペースを取得する
	// (GET /spaces/{space_identifier})
	GetSpace(ctx context.Context, request GetSpaceRequestObject) (GetSpaceResponseObject, error)
	// GetCurrentSpaceMember トークンの持ち主のメンバーを取得する
	// (GET /spaces/{space_identifier}/members/me)
	GetCurrentSpaceMember(ctx context.Context, request GetCurrentSpaceMemberRequestObject) (GetCurrentSpaceMemberResponseObject, error)
	// ListPages ページの一覧を取得する
	// (GET /spaces/{space_identifier}/pages)
	ListPages(ctx context.Context, request ListPagesRequestObject) (ListPagesResponseObject, error)
	// CreatePage ページを作成する
	// (POST /spaces/{space_identifier}/pages)
	CreatePage(ctx context.Context, request CreatePageRequestObject) (CreatePageResponseObject, error)
	// GetPage ページを取得する
	// (GET /spaces/{space_identifier}/pages/{page_number})
	GetPage(ctx context.Context, request GetPageRequestObject) (GetPageResponseObject, error)
	// UpdatePage ページを更新する
	// (PATCH /spaces/{space_identifier}/pages/{page_number})
	UpdatePage(ctx context.Context, request UpdatePageRequestObject) (UpdatePageResponseObject, error)
	// ListTopics トピックの一覧を取得する
	// (GET /spaces/{space_identifier}/topics)
	ListTopics(ctx context.Context, request ListTopicsRequestObject) (ListTopicsResponseObject, error)
	// GetTopic トピックを取得する
	// (GET /spaces/{space_identifier}/topics/{topic_number})
	GetTopic(ctx context.Context, request GetTopicRequestObject) (GetTopicResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetOpenAPIDescription operation middleware
func (sh *strictHandler) GetOpenAPIDescription(w http.ResponseWriter, r *http.Request) {
	var request GetOpenAPIDescriptionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIDescription(ctx, request.(GetOpenAPIDescriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIDescription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenAPIDescriptionResponseObject); ok {
		if err := validResponse.VisitGetOpenAPIDescriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSpace operation middleware
func (sh *strictHandler) GetSpace(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier) {
	var request GetSpaceRequestObject

	request.SpaceIdentifier = spaceIdentifier

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpace(ctx, request.(GetSpaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSpaceResponseObject); ok {
		if err := validResponse.VisitGetSpaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentSpaceMember operation middleware
func (sh *strictHandler) GetCurrentSpaceMember(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier) {
	var request GetCurrentSpaceMemberRequestObject

	request.SpaceIdentifier = spaceIdentifier

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentSpaceMember(ctx, request.(GetCurrentSpaceMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentSpaceMember")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentSpaceMemberResponseObject); ok {
		if err := validResponse.VisitGetCurrentSpaceMemberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPages operation middleware
func (sh *strictHandler) ListPages(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, params ListPagesParams) {
	var request ListPagesRequestObject

	request.SpaceIdentifier = spaceIdentifier
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPages(ctx, request.(ListPagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPagesResponseObject); ok {
		if err := validResponse.VisitListPagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePage operation middleware
func (sh *strictHandler) CreatePage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier) {
	var request CreatePageRequestObject

	request.SpaceIdentifier = spaceIdentifier

	var body CreatePageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePage(ctx, request.(CreatePageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePageResponseObject); ok {
		if err := validResponse.VisitCreatePageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPage operation middleware
func (sh *strictHandler) GetPage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, pageNumber PageNumber, params GetPageParams) {
	var request GetPageRequestObject

	request.SpaceIdentifier = spaceIdentifier
	request.PageNumber = pageNumber
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPage(ctx, request.(GetPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPageResponseObject); ok {
		if err := validResponse.VisitGetPageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePage operation middleware
func (sh *strictHandler) UpdatePage(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, pageNumber PageNumber, params UpdatePageParams) {
	var request UpdatePageRequestObject

	request.SpaceIdentifier = spaceIdentifier
	request.PageNumber = pageNumber
	request.Params = params

	var body UpdatePageApplicationMergePatchPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePage(ctx, request.(UpdatePageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePageResponseObject); ok {
		if err := validResponse.VisitUpdatePageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTopics operation middleware
func (sh *strictHandler) ListTopics(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, params ListTopicsParams) {
	var request ListTopicsRequestObject

	request.SpaceIdentifier = spaceIdentifier
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTopics(ctx, request.(ListTopicsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTopics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTopicsResponseObject); ok {
		if err := validResponse.VisitListTopicsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTopic operation middleware
func (sh *strictHandler) GetTopic(w http.ResponseWriter, r *http.Request, spaceIdentifier SpaceIdentifier, topicNumber TopicNumber) {
	var request GetTopicRequestObject

	request.SpaceIdentifier = spaceIdentifier
	request.TopicNumber = topicNumber

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTopic(ctx, request.(GetTopicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTopic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTopicResponseObject); ok {
		if err := validResponse.VisitGetTopicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F19VxPXuv8qWXPuH3YdMOHFVuly3aue9hx71Lpava5zi8sMyQBzDJM4mdRyu1grewISIFyU1hcKClgE",
	"JCXRY69FUPgwO5OEb3HXfva87HlNQC3a6z8KYWa/PPt5+T0v+8n3XCw5kEpKgqSkua7vuX6Bjwsy/PjZ",
	"Bb6P/B8X0jFZTCliUuK6OJz7CedeYnUDoxJWd7C6hHN5nCvi3FZ17pfqnVHyw1hWe/oAPv8R53JYLZMP",
	"Z3+t3nlSvfuoOqNiNIHVsfpqvla6i9FdjOaxuopzz3DuBlZ/1v8lgz/BaAWjmdChyvZEVyjazXVca2/9",
	"5PpnJ/8xcJT/27X+a7HEJ6e/6Pz7le/++sXAyb8OnjybPtI6+Df+dOTS1W4u+hHOqt2StjNXW/8Ro4K2",
	"NIbVKawWMHqiZZewqhqfjGO0jdEMPM61cLJwLSPKQpzrUuSM0MKlY/3CAE+IoQymBK6LSyuyKPVxQ0Mt",
	"3BlRuuomU/WXRUIghlgXvzpjbOarz0+FjrYfPYqzqr6vTCTSEQvzKTH8bVs4neJjQjqcFoR463XxqhhW",
	"kikxlv73WEZOJ+Xjhw8fhueFT0OykDjezUnCd4q52drznzCaxKhQG17EaFhb+FW7mceoXNm6B59vYzSL",
	"1R+MnQbt7CteEc6IA6LixQW/kI3l8lr++e7MTYxK1dLE7uiU87hgK1cGhIEeQe7mPpWPdx47duxT5Xjb",
	"0UhEX7B7KKwWsbpM2EHdAfJN1x5uAssgrI7B8a2RX9HPGM2/kQ2eTybE2GAz28S5+zi3htXfyOfBm712",
	"/EgkEvn0+vGOj9+JzQqKPHiiVxFk9z61G5P1x8v1xQJsaRKrEzD0Ckal2sp09bYuhjirNiMcoqQIfYIM",
	"s166dOlERukXJEWM8YrgnprIwsefHIlgVDop8LIg19cm66svgdQI534Gij0DEVoxJBQ0y0tQK8+wOr2b",
	"BVJ50SkUpYNGcRaRx+Cvjte1qbsY3QKK3mJIPuwaJCTIclI+3s2J0rd8QoxfUZJXBambi4b81kaO9wVW",
	"n8GZ38WoUH/+DJSNNX7oUGek46OQ9zTpTG+vGBMFSbmSjiVTQjfXEoIfjndzoBS6ZIGP0xWUsJrH6AZG",
	"xfoyIifIzqxO15Y2QdNu+xCx8moHoxvJlCDz5GQwKpMH0QuMlslIuiJ7sTsyWdmYCB2KGlrqe8r1Ypwc",
	"ca8oyENkMasY3ceoVNmYIFsrYqSSbWdRZ6QN57Y6Ix1kvegxRotwckWsqpgcz32dZMZ0ZIyd+/X130Do",
	"Xpkf4twiyMsofLJDVeqxT9qPkulA1arToagspJMZGWRS4eO8wh/v5voVJZXuCoeF7/iBVEI4HEsOhA9f",
	"FxKJ1qtS8roUTvIZpb81JScVIaYI8VZjDIdydm/beQo6Q+3Trgy1cCle5gcERbfGp0D5u+XH0PeMrSEs",
	"fUfbvksmJpI8T3QJ1TTkgVfEWhsMq41NOuyUYS1LoSgxLFeo1YmGsDqtnw/Z0nZ1Y9HOT5WN9fpmkQzw",
	"6qH2cgqjsjbyy+6dCXhqGaNxOOmfcBZVNvPaLSoEU4YBnsDoB2Cbgs4rxsC1OVS7/cjYymp1Lqvl7zu2",
	"W9/50b4WroUTCXGuZQR5kGvhJH6AUJduhWtkzz0tXhtLo8rWc1YptkUiZBXPRzDKY3WCQAtUJh+SDZHd",
	"V8eeYjRsLtBneQmYmV1dXOjlMwmF62qPtHC9SXmAV6h+7WjnWrgBURIHMgNcV1uLl+o9z/cJ5zLEGHkY",
	"NkbGtBsjDhao3V7Tpn4zt3dJ6KFCBWLvwfrhFN9HZIL8d0WCKYeiRBJXtZsFjO4BQVbse0/xSr+1debN",
	"QDHZKw2+Jks9ba40mBAYlerr97T8I239ZvOb39tGna/vEWxeIEp/L4fKQPB9nCsFnuHv4f/9nSz76hs8",
	"2iEyVDqVlNICqMeTfPwr4VpGSIPoxpKSIkjwI59KJQj0EJNSOCUnexLCwJ//mSb0+p6Z/N9koZfr4v4U",
	"tryhMP1rOnyevvUXQeHFRJrO7YSJa4TA6iqcQF73g1Dhi6+/PGfqgPraOuhhC7JxQy3c50m5R4zHBelA",
	"ls1ClSJo4FL1h8nKqzlvFGFTzibujF66dKmVBXnREM7dI0yXywJKLoWiAFoAJzUHTrgW1hN1TuC3df2V",
	"sBN0wt7PJZXPkxkpflD8YYKXgrZ+T5ujXLEGZmECZ1F9eQKrE9XVx+AWeBLaAS2r9+drG7PaSB6j1Rqx",
	"Rms6YU19pk5XC6Na6SfqYut4VlU7I50MYCVceF4WYkkpLpL1fs6LCeEgqBQ93dt6lldi/YCjQtHPLvB9",
	"5MeCA/tVtsZtf1+tbGTro78aDMSQyyaVhqMwAZCniLNIyz8iZIS4BMHmiwUjOrDMWutuKRqHVVOcn0UG",
	"urpbm/3VQDcTWB0zRqKfz8DpPiaAqLytjS57srmD9l+Z2vF3p76x+JI2Nlmdugn6gGAuk84EUDMnZJPw",
	"FZ2yOyNEvF0YjgPLlTzLS4O6kk4fiBTafW8TsZFlQgwKbBijd2wBkCCFYz3IRhVarbBCUy/rjxu+eqvp",
	"rAe+bbn1sOeLEnFgkrL430L8wG2KHoTCWVQbXtTGX0CQcH535qaWHyWCltvSlp5q4y+qG3mMdsAD3CYH",
	"gcpOXVdAGC1WNrZAHbgd12Fwg25ZGlSd1paegrvvkOW3YFkuSsJ3KfAWPyOe+wFQvbKZr87NWxZFXcW5",
	"xzj3koPVpTOpVFJWhPhZIS7yFwBKvSsYCTz53CjEex8a8eS7zqiMTa/b4zUTfgOEoidiMSFFpDCtuBRW",
	"A8TBvOoRLXMuYC87s8UMWcITgkOUcG9xAvsJnyfa+f/pMXsapibPmbz7ex30gCD3Ca0pMuWf93/o/8kn",
	"xDh/oIAN526BmlmkQTj4d9iPSNqNEa1E0G91/Wc4kSlPXwJin2mKtHK3IRn0ErJLY9rkvcqrSTLS7ald",
	"AtW84NSQQTY43XPC9fN8n0fQufJqrpq/qQeVrMCH5cim5GRKkBWROpc9yfhgQ3LxfcLJZHzwtJTKAAxQ",
	"RCUhNPPWBfKg9RrrLwdk34jhYzcR5Ohzew8eWcz4jdOFpxtroVS5bL6d7PmnEIMtnBO+U/zClc68mCNW",
	"6RWijJoRSDe/oaIjDumX/gpFpUwiwUTqOWPh3xhy1cKRR7jLeugsMPXZiFP8c6ZUIEKHzvLy1XjyuvSR",
	"x5JMSW/hxHjwcKf/4nnKmYwY9xpuIBkXe0UhfoVXgsfVxVWdrs5lte0CIbTh3WA0b2RxrXRmR0fHMYxK",
	"Fy+cMpOa7ZH2j1sjx1ojbRfa2rs6OruOfHy4rb2j88jH/2XkKlemq3Nr1c0sAL4HRHESVLdeW5mm+Sft",
	"ZpHiwupcUXuyjVEpglG5NoeM5Bfwh7mptCjFIMpQdEWqZ+0mwCRUnFeEVkUcELyoJb2J6CnhWvBbQ1Em",
	"ygmrpNCVDQu7xNQpmoxeaTIvb67D9mFJR+Y2lt6jlDSrqlBBe/pgv3qqgW4CNrdUU4CmsjO/l96yq/D9",
	"SnHt8Wb1zqi2flfL39UzWzSpyhyzi9PI1GfEdINZKxvZ+vIKRqW2JlSRqAgDaY/xIMpn4xavscy3G1kv",
	"YEm6HV6WeXBfmbxRoyEYW+E6WliCfTS/YzMBHB+nkRQ+cZ6hRi+fSAstQecJys3AKFStffH1l+dCZwlY",
	"C8HwRGcRhaQijOZ3F0ZqsyWMFgAaTjPK0UqwQvBHf1BVLdkqQnJ1xZHA10o/1bYfG/GkYerJGW9P6xND",
	"Dqyzvd0n6XVQsGXI51iYZ/ahsBhdAVp2ZXd0sr406iZdtxQNR3FuK9rdDf91kX+1/HNte5GKIkZl0LV5",
	"moDURvK7C+uQTaRmpegIm9ZelVz+CFEg/HdnBKlP6ee62iMRwFDG721eQm1H0J6lD8c6j3yCUUl/NKQ/",
	"6y/VNBLpJ9a1mc3aj/MYFbXZzercGEal+tov1Xv/05w+p9jb66QCgbiJ08jIELANRb81vZPWXnBPIKZr",
	"vFCkcqNbdzYr2pTWsZGVhlw8lFBa4ZWMx27+duHCeTjuGzqMtFIRYx5QrLHlNXZVqq2WdhcfkB/m1zEa",
	"9iM9wyGK7qQHD6hO1xdXMZq5+NVpy8roc/0I+aWikUYf00tLaFoui4gjmlvH6hMAzgu0pEfLL0Hou2jI",
	"hKWyfOhS2XpU2RgnejI3oi08hcQCgkAdzGbxQTkU5XuSGaWrJ8FLV22FMTZ4Kotucji9DvJXy4brx9li",
	"SICnJfDgDA9utqcFUKm6NAcVRyv15QmMlswqojb4xcnmTYukeYxNMIJZ6xEwDPGX9folpx8UOqSjzNyW",
	"vrfcGvmZiYVAYYx2cxKyHww0tQ9U2XqkLd2xb3qPqDCVJCLTmPBWZMBk99JodSxLs1YYzYD9PU9HCx0i",
	"zJ+7TZZLmHkRikXzeqkJeByh6J/CwCxRBozRSV57Vw7W1E/c2it7gF6MCWUIjYoPfIFcvGHZwh69QPF1",
	"CiIYf8ZZMODj1Lj9KigNaDCzg1cb6gvYqq2wAqbxPY6zQmPnzgjuPcO5m2bBp9cZ8Yrfnh6CBOZxbhJU",
	"6ULoUPQ/qDEErxriFVN0r/sKBbCrY/mA1mdUNjfJJ6pq35VuNYys8binC+rHPd47rS+u1pY2tZvWidVX",
	"143cswVozYCM3U3a0yHrxA44YCiT8aIW633663PmneAhnKr9jWzZ76RtE+9R4n240z5mQ4nbW0QkyNNn",
	"lAjrs+8/KvKtmBZ7xISoDDbeJpQl1srD2uy/LPCayvQkxBhZQLm+9oQKDdRkQEGwOqEXM7JDZVE0JYvf",
	"0ooXPWVpTlPUplRtfMHiBT2FYQorLQ4A/xEV2Jl27z/wmMwGpAQpM0DEgS4aOBjWwQhDkACZARJdjlhy",
	"2UjpK1t+sQobod9WuMJbiJvyHahiOOCQBXFOhFhGFpXBr8mYlABQeNzupsCXJzJKf6j9cASj0gk9tQ+e",
	"VehUMi6E/hw6//dTn4UOfd1+5GMwIGZ1ChT+PgTItaVjXSuj7lOvTpgaJgTDdRcg23RtZmu38C9jRNaO",
	"FGkNEka3oWzG9CO0kVWbRhh5upv9iYoewWtksscQ7X1IcRyduL42qU2V68uo+lQF1WDUXnuH/lcclvrE",
	"+dNGOSMNQHuVejeq4ibgkS2b8i5KN/dti/f4ErtUnRvTxl9U5+Z37/yAUbmtOqPCT9RFWwNg+wuw9G84",
	"98hxUkZsyRZEpP5UInmdwg+WLwhbuD68KCe4Lo5Wt4fNChHIOvbKQrrf9ne41wCFyMkUZc4U3yfAXQNH",
	"DgqKGrOAf/uEruuyqAjeWSrj/pdeVHQoao4IpUVsKOAjI5BrTchIvDEnzqo+ilK/e+BephGN/cHjXsYy",
	"MmEQzcJdFSQPmrCRLiqvxOMR5HRS4hMnYjEhnb4ADwZaSAMmrNRmNuHSDZTnZScIWmsssexLQeKYRfRJ",
	"yNQUd9EGVn8gBse285JpB13BAKMSnWy2B26mWJaXiBZNCYtSb9LIPfMxMAp65e8l8aooJbkWLgN0NKSx",
	"T1T6Mz0gjNfhCT6V0n/iXClmOoZptC8JPSEQc5MY5Dd1Wrv1EqNn2ugmlN0VqToJpPgM1OkHU3zCUIZE",
	"+4YO+Srf5tUulCuww3SF9PtJngV1485oMr0tU7KPqepximBe8FRjWnmbksKo+qVwxB0YItpNrynCqOwf",
	"uAwdivpVHlC33BW19rmI5IrSGIfqWxdWCnDcjJDliql5VTim8SORSKSy9Rwed9zMcxYxdkvUpXJNY7Of",
	"jXhqlVpXslpfHoEq3SnIWS7DNZM8zqJAf66wi27DgT2hgT39LWvpxu3M8unPLnxObMrqTHXzjla4U9lY",
	"B1PrLFqMhsLMhy72ZI/RMLfOIbpCDa5EEgBtvuTxtNdt0eg1wNrOcwS0OU7OLYui1+ER+kT1wYJ1iTGL",
	"ojL9W2lCf4le5MmiqOJ8qQA1iuPV2R3jgpL3jchuSZ+ZuQEESZpjVpImixrfsCS6gan7bKqSKZ0ZGODl",
	"QVZRerEnYxoZo0gVKTGNaKc6uwHogugCM+hqjEpULvELBDmt34U6HDkcIco6mRIkPiVyXVzH4bbDbYAD",
	"lH5ADGH9b4cH+QEIjvYJih+8p8jty5RA1Hl99V59h5DjHyfOnnFrDIe8MYbbuFUBy6K3GE8T+PBXQdGH",
	"/ovNz7HdH2mPRAIqqIw9BN7Xc8B2djfUsOl3uby9C3M1YWc5KesvcF3fXGaP3UkztpiGnCPflyZ+iXFO",
	"EMn0B7/+x2RXUAz6nXdkzlz6nWZBA92GeafZtd2Bti4wGkZqRTfuForxYINuaS/3I/TbhZ2RTp/Mqoul",
	"aEjXfkvzG++jtR4JO++jDV3eEx/urYKPLrFRkbb/cb4TxfBk9Z2RtmbEhil8h5c6G79kXgoiL7Qfa/yC",
	"8xrDawu2KcrNy5iPkIM4NxLxMLWu6TCNB76WtIP1aoDJ2JCXh2RBqK30Psr/qYwsC5LCphLefWWgL7Th",
	"vQ3fM/ygEg5MJQQKVpBK0AF1Q80Al7hfXynorrp+pcceh8FZZG8DVDKqpoZ3F6B1hVP0KhsTBjbVyznt",
	"XQX0HAsTIF4F7fArzs3XSk+JjzvyyEAZ5jNlJt5k6gufcBIbfHZ7oAU9gWGFsugpBarFghGhsse12GyD",
	"njPyrpQhXrMrb7LiGI44Ne7K2BUb/dXp2v8+wOp4ffulcTdZd3XHJrXZB+QwgbEqW492ZyaZIuDbLpLq",
	"hXD2zhO60+4YjTy2MkHr6MyFhLzKeF1NJghD0KRCma0Vr955AS0nVrT8DW3sX/qFaycvmbXh4NmbNC5D",
	"fbFejOBseoFWQ9EzIpSyMO5Y6FDU3noJKOsqbXe5bAHV6fZZC7ZqwTXaPMVjIf6tgOwG64yYVs6DfL+2",
	"kWrxS9FY3Gck+0r+kqSzi+uMnHejbTw9bImIx1+dxhxnUe3xppWHar5PiKOMeN/tJ7wpRVneKpv/KNS8",
	"eDl2wF7vNlTqIlZHoQPN46ABVdWj+s6DFHah9CZGQA09oUEDBjNSaY2f1BHE20RJZh22J0RyVmLb0ZDR",
	"CC4Iy8AzztZq7wVy6mj8ktXLYn9Yq73xC65bbwcG0qyAjJW6/YbJk10mDO2ZGbI/ddkO+FzF/r7Yjgyi",
	"F9w1ysWbxResvnCUK3jdLGPSn07oZapQH9RU9L2p5h3JL9DbMTSFCGYPiifyGC17I6wlv2YDb9qGuICW",
	"WUWoN3bxKce306PMojvnJXbn/XY35Wju11ZN5OOrdkv2Yvpy82X0Rn7Ddk+IvcYDlC5g9MRnyyaKuiRe",
	"FSGv/Qw27+p4wuyQ1nqyWOyS0FP7cWv3/kO9WllnOr3jEEZTRtKcDA7uvQ10sR5Dbfx5dWQCkpsGR7OU",
	"YlqdnUlSe+GGV9ab8852nllkNMewvxOK9gkAt6LenZI8ANopWeAVAS7UvJkwAui5k/oNkDdiG43btF79",
	"B7zv03qBwtyWd9dY3waTQy5z3/ZGzX3QfmyHbrf2RnfcIPsLzwy1cAZz+V9E9uIu2wVy396wtPVaZ/ve",
	"b5EfMAqJNDa8TFOvdxm4tB1pZl0eXTj+UKiHFv80hD3GYz64xw4W3HCniRCWvQ9hQEBLn9MTHQUEsV4/",
	"RtUwQKW3A7NQSjOxKR9A0PhVtj4qAJrp+Ot1kJnN5HqazrfTXtwjruVah97f6lxSEgKbXFFU6OwpbnUa",
	"soE0ExHRgE9H8/mFNwMFGjvVTJdQd8AigFxWJbe7dawnUW5R6OhJAiP4QE2GFX2wnUdg39a3HRQIDAjs",
	"HxkcoAXuoHbO3YPPJgG2RnueZ81035vXU3VmPNV20FZ9xvtHrA9Bk/chaNJErMS70dM+sYDz4vqqyfY4",
	"i5ztA2jA95OOY7RM37NjgPcNyWLjrgNZZDxjNcE3Hi4TbaxXA+4h2WUN/zuFbWwNQ+wBA6N16XCDtJrH",
	"4vcSOfHtb1m0efT05s4K7Q6mTd2h5GaAhPFNA8vQ5WoBo9vQBFG1z+DKAnW2H6WsY4+53DcvC9qj+dSy",
	"LjONUhlVbN9wm2e4hn7s2AZBnewKLJmy2p1qS2PV2V/hT5PVewtsD1Si+42ULoMV7K1R73qR5kPgqtnA",
	"VYAEsEuo/ba6O3uDFvgyY5fNJLx+EKqqjY3vziy5G+h6KjdUgAa8RljL/EaSV7exqhoDz+qd/qFVb6NW",
	"/XbsezEVf2ORsNeEv349cVkLEAiIfVsVzzD5Z6LMvayB45sPqHbwTWF6QOcmUXMzkUJnz8K9gWfanSeg",
	"6TDZomGudDK6zWeDJooh962JJmKJb99LYPumvd8ewx8qZtcEbvboir6PcJ+jJevrgfaje1u12U/8jxww",
	"ZJXIXgOG9Asu3kDRm7v4yrMgRnsyRSGPT7mbDyx/h+rOPtRf7bf+6gLltd8B1LxTJTVWvwC/smNnx4AP",
	"ZTUfIkR2e8FcBw+yF7bHLrsqqV2dKXzjRTBQk8bD8e1Iwbak6YKc5hM5B2UbzKuN5EW1YPTYKu/hDgXt",
	"xvE7KET2a7PevrJrpOje90sUH3TW76+zGqsq35UEzE5nFORvDdHzruwew+o69CXR2+5hdXp3ZLKys2jv",
	"bjRrdlSkF4Zp3we9cgXkTl/0/mE27T/p+Do9r5p0/14Azu/i02/HNDGGTYLZUvFmXrYcf+YrD32r6T1u",
	"RFtvGrd5hy4P/V8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
