// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"context"

	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
	"github.com/wikinoapp/wikino/go/internal/model"
	"github.com/wikinoapp/wikino/go/internal/templates"
)

// APITokenScopeBadgesはトークンに付与したスコープをバッジで並べます。
func APITokenScopeBadges(scopes []model.Scope) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<ul class=\"flex flex-wrap gap-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, scope := range scopes {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li class=\"badge bg-muted text-muted-foreground font-normal\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(APITokenScopeLabel(ctx, scope))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/api_token_scope.templ`, Line: 15, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// APITokenScopeLabelは公開APIのトークンのスコープの表示名を返します。個人アクセストークンの画面と
// OAuthの同意画面が同じ表示名を使います。トークンに付与できるスコープ (model.APITokenScopes)
// 以外が保存されていても画面が崩れないよう、表示名の無いスコープはスコープの文字列をそのまま
// 返します。
//
// 文言のキーはスコープの文字列から組み立てず、ここで名指しします。画面が持つキーをgrepで
// 追えるようにするためです。
func APITokenScopeLabel(ctx context.Context, scope model.Scope) string {
	switch scope {
	case model.ScopeTopicRead:
		return templates.T(ctx, "api_token_scope_topic_read")
	case model.ScopePageRead:
		return templates.T(ctx, "api_token_scope_page_read")
	case model.ScopePageWrite:
		return templates.T(ctx, "api_token_scope_page_write")
	default:
		return string(scope)
	}
}

// APITokenScopeHintはスコープで何ができるようになるかの説明を返します。
func APITokenScopeHint(ctx context.Context, scope model.Scope) string {
	switch scope {
	case model.ScopeTopicRead:
		return templates.T(ctx, "api_token_scope_topic_read_hint")
	case model.ScopePageRead:
		return templates.T(ctx, "api_token_scope_page_read_hint")
	case model.ScopePageWrite:
		return templates.T(ctx, "api_token_scope_page_write_hint")
	default:
		return ""
	}
}

var _ = templruntime.GeneratedTemplate
