// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"context"
	"strings"
	"unicode"

	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
	"github.com/wikinoapp/wikino/go/internal/templates"
	"github.com/wikinoapp/wikino/go/internal/viewmodel"
)

// BreadcrumbItemはパンくずリストの1項目を表す。
type BreadcrumbItem struct {
	Label    string
	Path     templates.Path
	IconName viewmodel.IconName

	// IsCurrentは現在のページを表す。現在項目はリンクにせずaria-current="page" を付ける。
	IsCurrent bool

	// AriaLabelはLabelが空のアイコンのみの項目をラベル付けする。
	AriaLabel string
}

// HomeBreadcrumbItemsはログイン済みの閲覧者に先頭のホーム項目を返し、未ログインでは何も返さない。
// /homeは認証必須のため、未ログインでも到達できる画面が経路の起点として提示してはいけない。リンクは
// 未ログインの訪問者をログイン画面へ送ってしまい、同じ項目列から作るBreadcrumbList JSON-LDはそれを
// ページの正規の親として宣言してしまう。認証必須の画面は常にtrueを渡す。
func HomeBreadcrumbItems(ctx context.Context, signedIn bool) []BreadcrumbItem {
	if !signedIn {
		return nil
	}

	return []BreadcrumbItem{
		{
			Path:      templates.HomePath(),
			IconName:  "house-regular",
			AriaLabel: templates.T(ctx, "breadcrumb_home"),
		},
	}
}

// defaultBreadcrumbHeaderMaxWidthClassは、画面がMaxWidthClassを空のままにしたときにヘッダーが
// フォールバックする幅。多くの画面が渡す値であり、渡し忘れた画面でもバーがビューポート端まで伸びず、
// ヘッダーが本文コンテナに揃う。
const defaultBreadcrumbHeaderMaxWidthClass = "max-w-3xl"

// BreadcrumbHeaderDataはパンくずヘッダーに渡すデータ構造体です。
type BreadcrumbHeaderData struct {
	Items []BreadcrumbItem

	// StructuredDataBaseURLはBreadcrumbList JSON-LDを有効にし、リンク項目を絶対URLにする
	// 接頭辞を渡す。未ログインでも到達できるルートの画面が渡し、認証必須の画面は空のままにする。
	// クローラーがたどれない経路を機械可読なデータとして出さないためである。公開ルートの画面は、個々の
	// 応答が非公開になり得ても (非公開トピックのページ・ゴミ箱のページ) これを渡す。その応答が届くのは
	// 読む権限をすでに持つ閲覧者だけで、クローラーは同じURLで404を受けるためである。
	StructuredDataBaseURL string

	// MaxWidthClassはヘッダーのコンテナのmax-widthクラス。各画面が本文コンテナと同じ値を
	// 渡すことで、パンくずの左端とナビバーの右端が本文と揃う (例: "max-w-3xl")。空の値が既定幅に
	// 解決されるよう、直接ではなくResolvedMaxWidthClass経由で読む。
	MaxWidthClass string
}

// ResolvedMaxWidthClassはヘッダーのコンテナに付けるmax-widthクラスを返し、画面が渡していない
// 場合は既定幅にフォールバックする。フォールバックが無いと、空の値はmax-widthの付かないコンテナに
// なり、ヘッダーがビューポート端まで伸びてナビバーの右端が本文と揃わなくなる。
func (d BreadcrumbHeaderData) ResolvedMaxWidthClass() string {
	if d.MaxWidthClass == "" {
		return defaultBreadcrumbHeaderMaxWidthClass
	}
	return d.MaxWidthClass
}

// hasNavigableItemsは経路に移動先の項目が1つ以上あるかを返す。現在項目 (リンクにせず描画する)
// だけの経路は上位へ戻る手段を持たないため、たどる先の無いナビゲーションランドマークを描画せず
// パンくずごと落とす。親が認証必須の公開画面は、未ログインの閲覧者にホーム項目を出さなくなった結果
// この状態になる。
func (d BreadcrumbHeaderData) hasNavigableItems() bool {
	for _, item := range d.Items {
		if item.Path != "" && !item.IsCurrent {
			return true
		}
	}

	return false
}

type breadcrumbListStructuredData struct {
	Context         string               `json:"@context"`
	Type            string               `json:"@type"`
	ItemListElement []breadcrumbListItem `json:"itemListElement"`
}

type breadcrumbListItem struct {
	Type     string `json:"@type"`
	Position int    `json:"position"`
	Name     string `json:"name"`
	Item     string `json:"item,omitempty"`
}

// breadcrumbListStructuredDataはUIと同じ項目から機械可読なパンくずを作り、順序・ローカライズ
// された名前・正規リンクがずれないようにする。
func (d BreadcrumbHeaderData) breadcrumbListStructuredData() *breadcrumbListStructuredData {
	if d.StructuredDataBaseURL == "" || !d.hasNavigableItems() {
		return nil
	}

	items := make([]breadcrumbListItem, 0, len(d.Items))
	for _, item := range d.Items {
		name := item.Label
		if name == "" {
			name = item.AriaLabel
		}
		if name == "" {
			continue
		}

		listItem := breadcrumbListItem{
			Type:     "ListItem",
			Position: len(items) + 1,
			Name:     name,
		}
		if item.Path != "" && !item.IsCurrent {
			listItem.Item = strings.TrimRight(d.StructuredDataBaseURL, "/") + string(item.Path)
		}
		items = append(items, listItem)
	}

	if len(items) == 0 {
		return nil
	}

	return &breadcrumbListStructuredData{
		Context:         "https://schema.org",
		Type:            "BreadcrumbList",
		ItemListElement: items,
	}
}

// BreadcrumbListStructuredDataは絶対ベースURLを指定したヘッダーにBreadcrumbList JSON-LDを
// 描画する。templ.JSONScriptがJSONエンコードするため、ラベルがscript要素の外へ脱出することはない。
func BreadcrumbListStructuredData(data BreadcrumbHeaderData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if structuredData := data.breadcrumbListStructuredData(); structuredData != nil {
			templ_7745c5c3_Err = templ.JSONScript("", structuredData).WithType("application/ld+json").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// BreadcrumbHeaderRenderDataは、独立して供給されるパンくずヘッダーとグローバルナビのデータを、
// BreadcrumbHeaderに渡す1つの値へまとめる。
type BreadcrumbHeaderRenderData struct {
	Header    BreadcrumbHeaderData
	GlobalNav GlobalNavData

	// HideGlobalNavはヘッダーからナビバーを落とし、パンくずをヘッダーの唯一の中身にする。
	// グローバルナビの対象外にする画面が指定する。
	HideGlobalNav bool
}

// ShouldRenderはヘッダーに描画する中身があるかを返す。falseになるのは、画面がたどれるパンくず
// 項目を持たず、かつグローバルナビの対象外である場合だけ。ヘッダーの両方の枠が空になり、描画すると
// 中身の無いbannerランドマークが残ってしまう。
func (d BreadcrumbHeaderRenderData) ShouldRender() bool {
	return d.Header.hasNavigableItems() || !d.HideGlobalNav
}

// BreadcrumbHeaderはパンくずヘッダーを描画する。本文と同じ幅のコンテナの中で、左にパンくず・右に
// グローバルナビバーを置く。パンくずはバーを潰さずに折り返すため、パンくず側にmin-w-0・バー側に
// shrink-0を付ける。
//
// グローバルナビの対象で、たどれるパンくず項目のない画面もバーのためにヘッダーを描画し、たどる先の無い
// パンくずランドマークを出す代わりに左側を空のままにする。その画面ではバーがヘッダーの唯一の中身に
// なるため、ヘッダーはバーと一緒にmdで切り替わる。md未満では両方が隠れ、中身の無いbannerランド
// マークが残らない。表示状態がflexではなくblockなのは、ヘッダーが単一のコンテナを通常フローで
// 並べるためである。
//
// 上余白はレイアウト側のラッパーから受け取らずヘッダー自身が持つ。md未満で自身を隠す画面では、余白も
// ヘッダーと一緒に消えるようにするためである。ラッパーだと本文の上に空白だけが残ってしまう。
//
// ShouldRenderがfalseのときは何も出力しないため、どの呼び出し側も中身の無いbannerランドマークを
// 残せない。ヘッダーと一緒に自身のマークアップを落とす呼び出し側は、自身でもShouldRenderを見る。
func BreadcrumbHeader(data BreadcrumbHeaderRenderData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if data.ShouldRender() {
			var templ_7745c5c3_Var3 = []any{"pt-4",
				templ.KV("hidden md:block", !data.Header.hasNavigableItems())}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var3).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 = []any{data.Header.ResolvedMaxWidthClass(), "mx-auto flex w-full items-center justify-between gap-2 px-4"}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var5).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><div class=\"min-w-0\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Header.hasNavigableItems() {
				templ_7745c5c3_Err = breadcrumbNav(data.Header.Items).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !data.HideGlobalNav {
				templ_7745c5c3_Err = GlobalNavTopBar(data.GlobalNav).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></header>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// breadcrumbLabelClassはラベルを描く幅の上限。上限を超える項目は、必要以上に行数を増やす
// のではなく省略記号で切る。スペース名もページタイトルも自由入力のテキストで、どちらも単独で
// 携帯電話の画面幅を埋める長さになりうるため。全文はDOMに残るので、スクリーンリーダーは全体を
// 読み、ポインタはtitle属性で全文を呼び戻せる。
//
// 上限を付けた項目が1行に収まらないときは、経路はこれまでどおり折り返す。必ず1行に収まる
// ところまで上限を厳しくすると、短い名前まで意味なく切られてしまう。
const breadcrumbLabelClass = "max-w-48 truncate"

// breadcrumbLabelTitleThresholdは、breadcrumbLabelClassが切り詰めうるラベルとして扱う
// 半角単位の幅。max-w-48は12remで、text-smではおよそ27単位が収まる。しきい値をそれより
// 下に置くのは、見積もりが境界付近に置いたラベルにもツールチップを残すため。収まっていた
// ラベルに付いたツールチップは繰り返しで済むが、付かなかった場合は切り詰めた文字列を
// 取り戻す手段が無くなる。
const breadcrumbLabelTitleThreshold = 24

// breadcrumbLabelNeedsTitleは、breadcrumbLabelClassが切り詰めうる長さのラベルかを返す。
// title属性を付けるのはそのときだけとする。全体が描かれるラベルでは画面に出ている文字列を
// 繰り返すだけで、ポインタが通り過ぎる項目ごとにツールチップが出るため。
//
// 切り詰めが起きるかは幅の問題で、サーバ側では測れないため、長さで代用する。ASCIIの外の
// ルーンを2単位と数えるのは、これらのラベルが主に持つ日本語が、同じ大きさのラテン文字の
// およそ2倍の幅で描かれるため。
func breadcrumbLabelNeedsTitle(label string) bool {
	units := 0
	for _, r := range label {
		if r > unicode.MaxASCII {
			units += 2
		} else {
			units++
		}

		if units > breadcrumbLabelTitleThreshold {
			return true
		}
	}

	return false
}

// breadcrumbNavはパンくずリストを描画する。
func breadcrumbNav(items []BreadcrumbItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<nav aria-label=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(templates.T(ctx, "breadcrumb_label"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 245, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\"><ol class=\"text-muted-foreground flex flex-wrap items-center gap-1.5 text-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i, item := range items {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "   ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if i > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<li class=\"leading-none\" aria-hidden=\"true\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templates.DecorativeIcon("caret-right-regular", "size-3.5 fill-gray-500").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "     <li class=\"inline-flex min-w-0 items-center gap-1\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if item.IsCurrent {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " aria-current=\"page\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if item.Path != "" && !item.IsCurrent {
				if item.Label == "" && item.IconName != "" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<a class=\"hover:text-foreground transition-colors inline-flex items-center\" href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 templ.SafeURL
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(item.Path))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 268, Col: 114}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\" aria-label=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var10 string
					templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue(item.AriaLabel)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 268, Col: 144}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templates.DecorativeIcon(item.IconName, "size-4 shrink-0 fill-gray-600").Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</a>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<a class=\"hover:text-foreground transition-colors inline-flex min-w-0 items-center gap-1\" href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var11 templ.SafeURL
					templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(item.Path))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 274, Col: 39}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if breadcrumbLabelNeedsTitle(item.Label) {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " title=\"")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						var templ_7745c5c3_Var12 string
						templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.ResolveAttributeValue(item.Label)
						if templ_7745c5c3_Err != nil {
							return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 276, Col: 27}
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "\"")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, ">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if item.IconName != "" {
						templ_7745c5c3_Err = templates.DecorativeIcon(item.IconName, "size-4 shrink-0 fill-gray-600").Render(ctx, templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					var templ_7745c5c3_Var13 = []any{breadcrumbLabelClass}
					templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var13...)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "<span class=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var14 string
					templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var13).String())
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 1, Col: 0}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var15 string
					templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(item.Label)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 282, Col: 57}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</span></a>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else {
				if item.IconName != "" {
					templ_7745c5c3_Err = templates.DecorativeIcon(item.IconName, "size-4 shrink-0 fill-gray-600").Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, " ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if item.Label != "" {
					var templ_7745c5c3_Var16 = []any{breadcrumbLabelClass}
					templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var16...)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "<span class=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var17 string
					templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var16).String())
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 1, Col: 0}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if breadcrumbLabelNeedsTitle(item.Label) {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, " title=\"")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						var templ_7745c5c3_Var18 string
						templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.ResolveAttributeValue(item.Label)
						if templ_7745c5c3_Err != nil {
							return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 293, Col: 27}
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "\"")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, ">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var19 string
					templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(item.Label)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/breadcrumb_header.templ`, Line: 295, Col: 20}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</ol></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
