# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TwoFactorAuths::RecoveryCodeRegenerationForm`.
# Please instead update this file by running `bin/tapioca dsl TwoFactorAuths::RecoveryCodeRegenerationForm`.


class TwoFactorAuths::RecoveryCodeRegenerationForm
  sig { returns(T.nilable(::String)) }
  def password; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def password=(value); end
end
