# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.1"

gem "rails"

gem "bootsnap", require: false
gem "email_validator"
gem "enumerize"
gem "graphql"
gem "graphql-batch"
gem "pg"
gem "puma"

group :development, :test do
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-mocks"
  gem "rspec-rails"
  gem "rspec_junit_formatter" # Using on CircleCI
  gem "standard"
end

group :development do
  gem "active_record_query_trace"
  gem "annotate"
  gem "bullet"
  gem "listen"
  gem "spring"
  gem "spring-watcher-listen"
  gem "web-console"
end

group :test do
  gem "factory_bot_rails"
  gem "simplecov", require: false
end

group :production do
  gem "lograge"
end
