name: Build

on: [push]

jobs:
  sorbet:
    name: Run Sorbet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - run: bundle exec srb tc


  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - run: bundle exec rubocop

  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    services:
      postgresql:
        image: postgres:14.2
        ports:
          - 45432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: nonoto_test
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
        # Adding a health check via options
        # https://github.community/t5/GitHub-Actions/Github-Actions-services-not-reachable/td-p/30050
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Setup Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - run: bundle exec rspec

