name: Build

on: [push]

jobs:
  sorbet:
    name: Type check with Sorbet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Run type check
        run: |
          bundle exec srb tc

  lint_rubocop:
    name: Lint with RuboCop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Run RuboCop
        run: |
          bundle exec rubocop

  test_rspec:
    name: Test with RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    services:
      postgresql:
        image: postgres:14.2
        ports:
          - 45432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: nonoto_test
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
        # Adding a health check via options
        # https://github.community/t5/GitHub-Actions/Github-Actions-services-not-reachable/td-p/30050
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Setup Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RSpec
        run: |
          bundle exec rspec
