name: Formatter

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**.js"
      - "**.ts"
      - "**.tsx"
      - "**.css"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "**.md"
      - "**.toml"
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - "**.tsx"
      - "**.css"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "**.md"
      - "**.toml"
  merge_group:

jobs:
  oxfmt:
    name: Oxfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm fmt:check

  result:
    name: Result
    runs-on: ubuntu-latest
    if: always()
    needs: [oxfmt]
    steps:
      - run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
