package seed

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/wikinoapp/wikino/go/internal/query"
)

// Titles of the pages the link cluster is built from. They are constants
// because the pages name each other in their bodies: a wiki link has to spell
// the title of its target exactly, and a spelling that misses would silently
// create a second page instead of linking to the intended one.
//
// [Ja] リンクが集中するページ群を組み立てるためのタイトル。定数にしているのは、
// これらのページが本文で互いを名指しするため。Wiki リンクは対象のタイトルを
// そのとおりに書く必要があり、書き損じても失敗にはならず、意図した相手へ
// リンクする代わりに別のページを作ってしまう。
const (
	linkHubTitle              = "リンクハブ"
	linkTargetTitleFormat     = "リンク先 %02d"
	hubBacklinkTitleFormat    = "ハブ被リンク %02d"
	nestedBacklinkTitleFormat = "ネスト被リンク %02d"
)

// linkSourceSpec describes one group of pages that exist to link somewhere.
// The two groups differ only in how many there are, what they are called and
// what they link to, so they are generated by one loop over these specs.
//
// [Ja] linkSourceSpec は、どこかへリンクするために存在するページ群 1 組の内容。
// 2 つの組は件数・名前・リンク先しか違わないため、この仕様を回す 1 つのループで
// 生成する。
type linkSourceSpec struct {
	count       int
	titleFormat string
	// body builds the page's body from its own title. Each group links
	// somewhere else, so the link is written by the group's own builder rather
	// than passed in as a target title.
	//
	// [Ja] body は自身のタイトルからページ本文を組み立てる。組ごとにリンク先が
	// 異なるため、リンクはリンク先のタイトルを受け取るのではなく、その組自身の
	// ビルダーが書く。
	body func(title string) string
}

// generateLinkHub creates the pages whose link, backlink and nested backlink
// lists all hold more entries than fit on one page.
//
// The three listings under a page body paginate independently and at three
// different sizes, so one page carrying links in every direction is what makes
// all three reachable from a single screen.
//
// [Ja] generateLinkHub は、リンク一覧・バックリンク一覧・ネストしたバックリンク
// 一覧のいずれもが 1 ページに収まらない件数を持つページ群を作成する。
//
// ページ本文の下に並ぶ 3 つの一覧はそれぞれ独立に、しかも異なる件数でページングする。
// あらゆる向きのリンクを持つページを 1 つ置くことで、3 つすべてを 1 画面から
// 辿れるようになる。
func generateLinkHub(
	ctx context.Context,
	dbtx query.DBTX,
	out io.Writer,
	amt amounts,
	spaces *seededSpaces,
	topics *seededTopics,
) error {
	// The link targets are not counted here. They are created by the resolver
	// while the hub's body is being rendered, so the whole set of them is the
	// work of the single step that creates the hub.
	//
	// [Ja] リンク先ページはここでは数えない。ハブの本文をレンダリングする過程で
	// resolver が作成するため、その全体がハブを作成する 1 ステップの仕事に
	// あたる。
	bar := newProgress(out, "リンク集中ページ", 1+amt.linkHubBacklinks+amt.nestedBacklinks)
	defer bar.finish()

	owner, err := spaces.wiki.requireMember(roleOwner)
	if err != nil {
		return err
	}

	writer := newPageWriter(dbtx, spaces.wiki)

	if _, err := writer.createPage(ctx, createPageInput{
		topic:  topics.notes,
		author: owner,
		title:  linkHubTitle,
		body:   linkHubBody(amt.linkHubTargets),
	}); err != nil {
		return err
	}
	bar.advance()

	// The nested backlinks are hung on the target the link list shows first,
	// so that the nested listing can be paged through without paging the link
	// list to reach it. That target is the last one the hub's body names: the
	// link list is ordered by modified_at descending, and the resolver creates
	// the targets in the order they are written.
	//
	// [Ja] ネストしたバックリンクは、リンク一覧が最初に見せるリンク先に付ける。
	// リンク一覧をページ送りしてそこへ辿り着かなくても、ネストした一覧の
	// ページ送りを確認できるようにするため。そのリンク先はハブの本文が最後に
	// 名指しするページになる。リンク一覧の並び順は modified_at の降順であり、
	// resolver はリンク先を書かれた順に作成するため。
	nestedTarget := fmt.Sprintf(linkTargetTitleFormat, amt.linkHubTargets)

	specs := []linkSourceSpec{
		{
			count:       amt.linkHubBacklinks,
			titleFormat: hubBacklinkTitleFormat,
			body:        hubBacklinkBody,
		},
		{
			count:       amt.nestedBacklinks,
			titleFormat: nestedBacklinkTitleFormat,
			body:        func(title string) string { return nestedBacklinkBody(title, nestedTarget) },
		},
	}

	for _, spec := range specs {
		for number := 1; number <= spec.count; number++ {
			title := fmt.Sprintf(spec.titleFormat, number)

			// The accounts take turns, as they do for the pages that fill the
			// listings, so that a home screen showing pages of its own is not
			// something only one of them has.
			//
			// [Ja] アカウントは順に担当する。一覧を埋めるページと同じで、自分の
			// ページが並ぶホーム画面を 1 つのアカウントだけが持つ状態にしないため。
			author, err := spaces.wiki.memberInTurn(contentAuthorRoles, number)
			if err != nil {
				return err
			}

			if _, err := writer.createPage(ctx, createPageInput{
				topic:  topics.notes,
				author: author,
				title:  title,
				body:   spec.body(title),
			}); err != nil {
				return err
			}
			bar.advance()
		}
	}

	return nil
}

// linkHubBody builds the hub's body: a short explanation of what the page is
// for, followed by one wiki link per target.
//
// The body carries no headings of its own. The page screen puts the page title
// above the body as an H1, and the link listing below it under a heading of
// its own, so a heading here naming either the page or its links would show
// the same words twice, once above the body and once below it.
//
// [Ja] linkHubBody はハブの本文を組み立てる。このページが何のためにあるのかの
// 短い説明に続けて、リンク先 1 件につき 1 つの Wiki リンクを並べる。
//
// 本文は見出しを持たない。ページ画面は本文の上にページタイトルを H1 として置き、
// 本文の下にリンク一覧を「リンク」の見出しで描画する。このページ自身やその
// リンクを名指す見出しをここに置くと、同じ文字列が本文の上と下に 2 回並ぶことになる。
func linkHubBody(targets int) string {
	var b strings.Builder

	b.WriteString(`下に並ぶページはすべてこのページからリンクしており、それがこのページのリンク一覧に並んでいる理由です。一覧が一度に見せる件数より多く用意してあるため、ページ送りを試せます。

これらのページはまだ書かれていません。誰も書いていないタイトルへの Wiki リンクは、その名前のページを未公開のまま作成します。ここに並ぶページはすべてそうして作られたものです。

最後に並ぶページが、リンク一覧が最初に見せるページです。一覧の並び順が最終更新の新しい順であるためです。そのページにはさらにそこへリンクするページが付いており、その下にネストして並ぶ一覧もページ送りが必要な件数になっています。

`)

	for number := 1; number <= targets; number++ {
		b.WriteString("- [[" + fmt.Sprintf(linkTargetTitleFormat, number) + "]]\n")
	}

	return b.String()
}

// hubBacklinkBody builds the body of a page that links to the hub.
//
// [Ja] hubBacklinkBody は、ハブへリンクするページの本文を組み立てる。
func hubBacklinkBody(title string) string {
	return fmt.Sprintf(`%s は [[%s]] へリンクするために存在するページです。

このようなページを、ハブのバックリンク一覧が一度に見せる件数より多く用意しています。
`, title, linkHubTitle)
}

// nestedBacklinkBody builds the body of a page that links to one of the hub's
// targets. The hub is named in plain text rather than as a wiki link: a link
// would put this page in the hub's own backlink list too, and that list is
// counted.
//
// [Ja] nestedBacklinkBody は、ハブのリンク先の 1 つへリンクするページの本文を
// 組み立てる。ハブは Wiki リンクではなくプレーンテキストで名指しする。リンクに
// すると、このページがハブ自身のバックリンク一覧にも入ってしまい、あの一覧は
// 件数を数えているため。
func nestedBacklinkBody(title string, target string) string {
	return fmt.Sprintf(`%s は、リンクハブがリンクしているページの 1 つである [[%s]] へリンクするために存在するページです。

リンクハブはそのページを一覧に並べ、その下にそこへリンクするページを見せます。このようなページが、ネストした一覧を一度に見せる件数より多くしています。
`, title, target)
}
