FROM node:12.16.3-alpine

LABEL maintainer="https://shimba.co" \
      description="A note taking app."

RUN apk update && \
    apk add -t \
        git \
        curl

ENV PATH=./node_modules/.bin/:$PATH

WORKDIR /web/

COPY package.json package-lock.json ./
RUN npm install

EXPOSE 3000
